crates/tinymist-query/src/completion.rs

same issue as https://github.com/nvarner/typst-lsp/commit/2d66f26fb96ceb8e485f492e5b81e9db25c3e8ec

dev: use implicit autocomplete

---

crates/tinymist/src/lib.rs
crates/tinymist/src/main.rs
crates/tinymist/src/transport.rs

The writer thread never closes because of the sender is not dropped.

feat: correctly drop sender after the server shutting down

---

Cargo.lock
Cargo.toml

Implements `World::packages` for package autocompletion.

feat: upgrade compiler for autocompleting package

---

Cargo.lock
Cargo.toml
crates/tinymist/src/actor/compile.rs
crates/tinymist/src/actor/typst.rs
crates/tinymist/src/init.rs
crates/tinymist/src/lib.rs
crates/tinymist/src/query.rs
crates/tinymist/src/utils.rs

feat: add capability to settle down a compiler actor

---

crates/tinymist/src/actor.rs
crates/tinymist/src/actor/compile.rs
crates/tinymist/src/actor/render.rs
crates/tinymist/src/actor/typst.rs
crates/tinymist/src/init.rs
crates/tinymist/src/lib.rs
crates/tinymist/src/main.rs
crates/tinymist/src/state.rs
editors/vscode/src/extension.ts

Let compiler start a root resolution only if there is no determined root and exactly after and an entry is determined.

feat: deferred root resolution

---

crates/tinymist-query/src/code_lens.rs
editors/vscode/src/extension.ts

+ Preview
+ Preview in ..
+ doc or slide mode
+ tab of browser
+ Export as ..
+ pdf

feat: support rest code lens

---

editors/vscode/.vscodeignore

fix: bundle `editor-tools` files

---

editors/vscode/src/editor-tools.ts
editors/vscode/src/extension.ts
tools/editor-tools/index.html
tools/editor-tools/src/icons.ts
tools/editor-tools/src/main.ts
tools/editor-tools/src/style.css
tools/editor-tools/src/vscode.ts

+ favorite or unfavorite by clicking a button.
+ filter list by favorite state.
+ get persist favorite state.
+ run `initTemplate` command with favorite state.

feat: add favorite function in template gallery

---

editors/vscode/src/extension.ts
tools/editor-tools/index.html

+ not favorited templates are shown in quick picker.
+ editor tool has wrong backend

fix: two bugs during initializing template

---

crates/tinymist-query/src/code_lens.rs
crates/tinymist-query/src/goto_declaration.rs
crates/tinymist-query/src/inlay_hint.rs
crates/tinymist-query/src/signature_help.rs
crates/tinymist-query/src/symbol.rs
crates/tinymist/src/actor/typst.rs

Check state of main source before all lsp requests. if not, typst compiler will panic...

fix: check state of main source before all lsp requests

---

Cargo.lock
Cargo.toml

feat: use ts and preview crates

---

crates/tinymist-query/src/lsp_typst_boundary.rs

fix: convert EOF position correctly

---

Cargo.lock
Cargo.toml
crates/tinymist-query/src/lib.rs
crates/tinymist/Cargo.toml
crates/tinymist/src/actor.rs
crates/tinymist/src/actor/formatting.rs
crates/tinymist/src/server/lsp.rs
crates/tinymist/src/server/lsp_init.rs
crates/tinymist/src/state.rs
editors/vscode/package.json

Add two formatters:
+ [typstyle](https://github.com/Enter-tainer/typstyle)
+ [typstfmt](https://github.com/astrale-sharp/typstfmt)

feat: support formatters

---

crates/tinymist/src/actor.rs
crates/tinymist/src/actor/formatting.rs

Poorman's implementation of the diffing algorithm, borrowed from [`Source::replace`].

feat: minimal diff algorithm for source formatting

---

Cargo.lock
Cargo.toml
crates/tinymist-query/Cargo.toml
crates/tinymist-query/src/analysis/global.rs
crates/tinymist-query/src/document_metrics.rs
crates/tinymist-query/src/lib.rs
crates/tinymist/src/actor/typ_client.rs
crates/tinymist/src/server/lsp.rs
crates/tinymist/src/state.rs
editors/vscode/package.json
editors/vscode/src/editor-tools.ts
editors/vscode/src/extension.ts
tests/e2e/main.rs
tools/editor-tools/src/features/diagnostics.ts
tools/editor-tools/src/features/summary.ts
tools/editor-tools/src/main.ts
tools/editor-tools/src/style.css
tools/editor-tools/src/vscode.ts

dev: init summary page

---

Cargo.lock
Cargo.toml
crates/tinymist/Cargo.toml
crates/tinymist/src/lib.rs
crates/tinymist/src/resource/mod.rs
crates/tinymist/src/resource/symbols.rs
crates/tinymist/src/server/lsp.rs
editors/vscode/package.json
editors/vscode/src/editor-tools.ts
editors/vscode/src/extension.ts
tests/e2e/main.rs
tools/editor-tools/package.json
tools/editor-tools/src/features/.gitignore
tools/editor-tools/src/features/symbol-picker.css
tools/editor-tools/src/features/symbol-picker.ts
tools/editor-tools/src/main.ts
tools/editor-tools/src/style.css
yarn.lock

feat: initialize symbol picker

---

Cargo.lock
Cargo.toml

https://github.com/Enter-tainer/typstyle/releases/tag/v0.11.11

chore: bump to typstyle v0.11.11

---

editors/vscode/src/extension.ts
editors/vscode/src/ui-extends.ts

+ remove focus on the file if the invisible document is closed.
+ remove the status bar until the last focusing document is closed

dev: optimize state transition of focusing file and status bar

---

Cargo.lock
Cargo.toml

chore: bump to typstyle v0.11.17

---

Cargo.toml
crates/tinymist-query/src/adt/snapshot_map.rs
crates/tinymist-query/src/analysis/global.rs
crates/tinymist/src/actor/typ_server.rs
crates/tinymist/src/server/compiler_init.rs
crates/tinymist/src/server/lsp_init.rs

build: upgrade rust and set MSRV to 1.75

---

crates/tinymist-query/src/code_context.rs
crates/tinymist-query/src/syntax/matcher.rs
tests/e2e/main.rs

dev: get check target without skip trivia node in non-code context

---

crates/tinymist-query/src/upstream/complete.rs
crates/tinymist/src/server/lsp_init.rs
tests/e2e/main.rs

feat: complete both open and closed labels

---

crates/tinymist-query/src/analysis/signature.rs

This PR generates parameter names for destructured patterns, as shown below.
```typ
#let foo((x, y, _, ..z)) = [ #x #y #z ]
#foo((1, 2, 3, 4, 5, 6))
```

feat: generate names for destructuring closure params

---

crates/tinymist/src/state.rs

The async version cannot steal twice.

refactor: simplify pin_entry

---

crates/tinymist/src/actor/export.rs

fix: accumulate export events correctly

---

Cargo.lock
Cargo.toml
crates/tinymist-query/src/analysis/global.rs
crates/tinymist-query/src/symbol.rs
crates/tinymist-query/src/tests.rs
crates/tinymist/src/actor/mod.rs
crates/tinymist/src/actor/typ_client.rs
crates/tinymist/src/actor/typ_server.rs
crates/tinymist/src/lib.rs
crates/tinymist/src/main.rs
crates/tinymist/src/resource/symbols.rs
crates/tinymist/src/server/lsp.rs
crates/tinymist/src/server/preview.rs
crates/tinymist/src/server/preview_compiler.rs
crates/tinymist/src/tools/package/init.rs
crates/tinymist/src/tools/package/mod.rs
crates/tinymist/src/tools/preview.rs
crates/tinymist/src/world.rs
crates/typst-preview/src/lib.rs

refactor: combine typst-preview and tinymist compiler

---

crates/tinymist/src/actor/typ_server.rs

fix: check main before compilation

---

.github/workflows/release.yml
crates/sync-lsp/src/lib.rs
crates/sync-lsp/src/req_queue.rs
crates/tinymist-query/src/analysis/def_use.rs
crates/tinymist-query/src/analysis/global.rs
crates/tinymist-query/src/analysis/import.rs
crates/tinymist/Cargo.toml
crates/tinymist/src/actor/typ_client.rs
crates/tinymist/src/actor/typ_server.rs
crates/tinymist/src/main.rs
crates/tinymist/src/state.rs
scripts/e2e.ps1

todo: limit maximum number of compilation?

feat: fully concurrent lsp

---

.github/workflows/release.yml
editors/vscode/src/extension.ts
editors/vscode/src/test/suite/index.ts
editors/vscode/src/test/suite/simple-docs.test.ts

~If server cannot process lagged compilation well, we will have lower possibility to pass it.~
This testing can be triggered locally, but not on CI.

test: increase the difficulty of diagnostic testing

---

crates/tinymist/src/init.rs

Found a test failure in https://github.com/NixOS/nixpkgs/pull/328756.
Fix an issue at the same time: when `typstExtraArgs` is unspecified, it doesn't pull values from environment variables.
cc @LamprosPitsillos @drupol

fix: retrieve environments even if `typstExtraArgs` is unspecified

---

Cargo.lock
Cargo.toml

https://enter-tainer.github.io/typstyle/changelog/#v01131---2024-08-08

chore: bump typstyle v0.11.31

---

crates/tinymist/src/init.rs
crates/tinymist/src/main.rs
crates/tinymist/src/server.rs
crates/tinymist/src/task/format.rs

fix: bad configuration initialization

---

crates/tinymist-query/src/completion.rs
crates/tinymist-query/src/fixtures/goto_definition/label.typ
crates/tinymist-query/src/fixtures/goto_definition/snaps/test@label.typ.snap
crates/tinymist-query/src/goto_definition.rs
crates/tinymist-query/src/tests.rs

I hope to implement `goto_reference` with labels, here is where I get started

test: add test for `goto_definition` for label

---

crates/tinymist-query/src/analysis/global.rs
crates/tinymist-query/src/analysis/import.rs
crates/tinymist-query/src/analysis/linked_def.rs
crates/tinymist-query/src/analysis/track_values.rs
crates/tinymist-query/src/hover.rs
crates/tinymist-query/src/prelude.rs
crates/tinymist-query/src/tests.rs
crates/tinymist-query/src/upstream/complete.rs
crates/tinymist-query/src/upstream/complete/ext.rs
crates/tinymist-query/src/upstream/tooltip.rs
crates/tinymist/src/actor/mod.rs
crates/tinymist/src/tool/preview.rs

dev: perform simple rate limit on heavy dynamic analysis

---

syntaxes/textmate/main.mts
syntaxes/textmate/tests/unit/bugs/tinymist-issue492.typ.snap

fix: parse dot issue 492 again

---

docs/tinymist/feature/preview.typ
docs/tinymist/guide/completion.typ
docs/tinymist/mod.typ

docs: add document preview feature documentations for non-vscode clients

---

docs/tinymist/configurations.typ
editors/neovim/Configuration.md
editors/vscode/Configuration.md
editors/vscode/package.json
editors/vscode/scripts/config-man.cjs

docs: add root path hints for neovim users

---

crates/tinymist-query/src/hover.rs
crates/tinymist-query/src/prelude.rs

feat: display all imported definitions for wildcard imports

---

crates/tinymist-query/src/lib.rs
crates/tinymist-query/src/syntax/lexical_hierarchy.rs
crates/tinymist-query/src/workspace_label.rs
crates/tinymist/src/cmd.rs
crates/tinymist/src/server.rs
editors/vscode/package.json
editors/vscode/src/extension.ts
editors/vscode/src/label.ts
editors/vscode/src/lsp.ts
tests/e2e/main.rs

feat: add label view

---

Cargo.lock
Cargo.toml
crates/tinymist/Cargo.toml
crates/tinymist/src/args.rs
crates/tinymist/src/main.rs

This PR adds completion support for Fig and Nushell.

feat: Add completions for Fig and Nushell

---

crates/tinymist-query/src/fixtures/folding_range/nested-blocks-2.typ
crates/tinymist-query/src/fixtures/folding_range/snaps/test@nested-blocks-2.typ.snap
tests/e2e/main.rs

fix: process overlapping cases in line folding only mode (3ab4fa62)

---

crates/tinymist/src/tool/package/mod.rs

The previous code asserts all directories in the package directory are typst packages, but this is not always true. Print errors once and skip these directories.

fix: allow user keeping garbage directories in the package directory

---

syntaxes/textmate/main.mts
syntaxes/textmate/tests/unit/basic/colon.typ
syntaxes/textmate/tests/unit/basic/colon.typ.snap
syntaxes/textmate/tests/unit/basic/control-flow-for-content.typ.snap
syntaxes/textmate/tests/unit/basic/control-flow-for-destruct.typ
syntaxes/textmate/tests/unit/basic/control-flow-for-destruct.typ.snap
syntaxes/textmate/tests/unit/basic/control-flow-for.typ.snap
syntaxes/textmate/tests/unit/basic/raw.typ.snap
syntaxes/textmate/tests/unit/basic/raw2.typ.snap
syntaxes/textmate/tests/unit/basic/raw_nest.typ.snap
syntaxes/textmate/tests/unit/bugs/tinymist-issue640.typ
syntaxes/textmate/tests/unit/bugs/tinymist-issue640.typ.snap
syntaxes/textmate/tests/unit/editing/for.typ.snap
syntaxes/textmate/tests/unit/editing/for2.typ.snap
syntaxes/textmate/tests/unit/editing/for3.typ.snap
syntaxes/textmate/tests/unit/editing/for5.typ.snap

using greedy expression end pattern trick.

feat: parse for clause correctly

---

crates/tinymist-query/src/fixtures/rename/snaps/test@module_path.typ.snap
crates/tinymist-query/src/fixtures/rename/snaps/test@module_path_alias.typ.snap
crates/tinymist-query/src/fixtures/rename/snaps/test@module_path_non_cano.typ.snap
crates/tinymist-query/src/fixtures/rename/snaps/test@module_path_star.typ.snap
crates/tinymist-query/src/lib.rs
crates/tinymist-query/src/rename.rs
crates/tinymist-query/src/will_rename_files.rs
crates/tinymist/src/init.rs
crates/tinymist/src/server.rs
tests/e2e/main.rs

feat: issue import changes request during `willRenameFiles`

---

Cargo.lock
Cargo.toml
crates/tinymist-derive/Cargo.toml
crates/tinymist-derive/src/lib.rs
crates/tinymist-query/Cargo.toml
crates/tinymist-query/src/analysis/ty.rs
crates/tinymist-query/src/analysis/ty/apply.rs
crates/tinymist-query/src/analysis/ty/post_check.rs
crates/tinymist-query/src/analysis/ty/select.rs
crates/tinymist-query/src/ty/apply.rs
crates/tinymist-query/src/ty/bound.rs
crates/tinymist-query/src/ty/builtin.rs
crates/tinymist-query/src/ty/def.rs
crates/tinymist-query/src/ty/describe.rs
crates/tinymist-query/src/ty/iface.rs
crates/tinymist-query/src/ty/mod.rs
crates/tinymist-query/src/ty/mutate.rs
crates/tinymist-query/src/ty/select.rs
crates/tinymist-query/src/ty/sig.rs
crates/tinymist-query/src/ty/simplify.rs
crates/tinymist-query/src/ty/subst.rs

To allow correct substitution on type terms.

feat: introduce type context trait `TyCtx`

---

crates/tinymist-query/src/adt/interner.rs
crates/tinymist-query/src/analysis.rs
crates/tinymist-query/src/analysis/global.rs
crates/tinymist-query/src/analysis/stats.rs
crates/tinymist-query/src/lib.rs
crates/tinymist-query/src/syntax/expr.rs
crates/tinymist-query/src/syntax/lexical_hierarchy.rs
crates/tinymist/src/actor/mod.rs
crates/tinymist/src/actor/typ_client.rs
crates/tinymist/src/lib.rs
crates/tinymist/src/server.rs
crates/tinymist/src/stats.rs
crates/tinymist/src/tool/preview.rs

Some code was occasionally added in #733

feat: show performance statistics in summary page

---

crates/tinymist/src/tool/word_count.rs

A simple fix for #793 , might require more tests

fix: wrong word count when empty line exists

---

crates/sync-lsp/src/lib.rs
crates/sync-lsp/src/req_queue.rs

This is helpful to debug which requests are stucking in e2e testing.

dev: add time limit to lsp replay command

---

crates/tinymist-query/src/analysis/global.rs
crates/tinymist-query/src/analysis/tyck.rs
crates/tinymist-query/src/analysis/tyck/apply.rs
crates/tinymist-query/src/lib.rs
crates/tinymist-query/src/ty/def.rs

- remove log on critical paths
- optimized `check_module_item`
- add and cache `constrain_call`

feat: improve caches of calls and module exports type checking

---

MAINTAINERS.typ

- Name: ParaN3xus
- GitHub: @ParaN3xus
I use vscode and maintain [typress](https://github.com/paran3xus/typress). I'm familiar with rust.
- Nightly Releases

feat: Request to be a maintainer

---

editors/vscode/package.json

add document in config for: "tinymist" for use Tinymist in Path

docs: desc tinymist serverPath

---

Cargo.lock
crates/tinymist-query/src/code_context.rs
crates/tinymist-query/src/lib.rs
crates/tinymist-world/src/font.rs
crates/tinymist-world/src/lib.rs
crates/tinymist/Cargo.toml
crates/tinymist/src/cmd.rs
crates/tinymist/src/init.rs
crates/tinymist/src/resource/fonts.rs
crates/tinymist/src/resource/mod.rs
crates/tinymist/src/resource/symbols.rs
crates/tinymist/src/server.rs
crates/typlite/src/tests.rs
editors/vscode/package.json
editors/vscode/src/editor-tools.ts
editors/vscode/src/extension.ts
editors/vscode/src/lsp.ts
tools/editor-tools/src/features/font-view.ts
tools/editor-tools/src/features/summary.ts
tools/editor-tools/src/main.base.ts
tools/editor-tools/src/main.ts
tools/editor-tools/src/types.ts
tools/editor-tools/src/vscode.ts

A quick implementation of a tool providing list of fonts used by the server.

feat: provide elementary font view

---

editors/vscode/package.json
editors/vscode/src/extension.ts
editors/vscode/src/features/package.ts
editors/vscode/src/features/tool.symbol-view.ts
editors/vscode/src/features/tool.ts

A tool view can be found by users at the side bar. This helps discover and use available tools. It can be optionally disabled by users by right click.

feat: provide tool view

---

Cargo.lock
Cargo.toml
editors/vscode/CHANGELOG.md
editors/vscode/package.json
syntaxes/textmate/package.json

build: bump version to 0.12.6

---

crates/tinymist-query/src/fixtures/completion/import_item.typ
crates/tinymist-query/src/fixtures/completion/import_item_immediately_colon.typ
crates/tinymist-query/src/fixtures/completion/import_item_immediately_comma.typ
crates/tinymist-query/src/fixtures/completion/import_item_mul_cross_line.typ
crates/tinymist-query/src/fixtures/completion/snaps/test@import_item.typ.snap
crates/tinymist-query/src/fixtures/completion/snaps/test@import_item_immediately_colon.typ.snap
crates/tinymist-query/src/fixtures/completion/snaps/test@import_item_immediately_comma.typ.snap
crates/tinymist-query/src/fixtures/completion/snaps/test@import_item_mul_cross_line.typ.snap
crates/tinymist-query/src/upstream/complete.rs

fix: `import "lib.typ": |` cannot complete
problem from #952

fix: import item complete

---

Cargo.lock
Cargo.toml
crates/tinymist/src/tool/preview.rs
tools/typst-dom/package.json
tools/typst-dom/src/typst-doc.mts
tools/typst-preview-frontend/package.json
tools/typst-preview-frontend/src/main.js
yarn.lock

ref https://github.com/Myriad-Dreamin/tinymist/pull/851

fix: compatibility for some old chromium core

---

crates/tinymist-query/src/fixtures/completion/field_simple.typ
crates/tinymist-query/src/fixtures/completion/func_pos_arg_field_call.typ
crates/tinymist-query/src/fixtures/completion/func_pos_arg_field_call2.typ
crates/tinymist-query/src/fixtures/completion/func_pos_arg_field_middle.typ
crates/tinymist-query/src/fixtures/completion/func_pos_arg_field_simple.typ
crates/tinymist-query/src/fixtures/completion/snaps/test@field_simple.typ.snap
crates/tinymist-query/src/fixtures/completion/snaps/test@func_pos_arg_field_call.typ.snap
crates/tinymist-query/src/fixtures/completion/snaps/test@func_pos_arg_field_call2.typ.snap
crates/tinymist-query/src/fixtures/completion/snaps/test@func_pos_arg_field_middle.typ.snap
crates/tinymist-query/src/fixtures/completion/snaps/test@func_pos_arg_field_simple.typ.snap

Noticed some bad cases when editing field accesses in a function call. I haven't fixed but written some test cases.

test: complete field access in function call

---

crates/tinymist/src/actor/typ_client.rs
crates/tinymist/src/actor/typ_server.rs
crates/tinymist/src/cmd.rs
crates/tinymist/src/task/export.rs

This was unblocked by most of our APIs becoming async.

dev: make compiler task async

---

Cargo.toml
docs/dev-guide.md

docs: doc preview dev

---

crates/tinymist-query/src/rename.rs

fix: rename request affect non-related paths

---

crates/tinymist-query/src/fixtures/rename/resources.typ
crates/tinymist-query/src/fixtures/rename/snaps/prepare@resources.typ.snap
crates/tinymist-query/src/fixtures/rename/snaps/test@resources.typ.snap
tests/e2e/main.rs

test: testcases for resource include

---

MAINTAINERS.typ

- Name: Sylvan Franklin
- GitHub: @SylvanFranklin 
I use neovim and understand plugin development and package managers like Lazy and Mason in the lua language. I'm familiar with both Rust and Typescript as well as Typst and it's related tooling. I maintain a couple of small Rust projects related to system architecture on macOS. I have experience with front end web technologies such as CSS, Svelte, and Vue. 
I have helped with documentation and technical writing on other Typst projects such at `utpm`, and regularly open issues on other open source projects.
I'm personally invested in the success of this tool, especially as it is integrated into neovim which is my favorite editor. 
- #editor-integration
- #document-previewing

feat: add SylvanFranklin

---

crates/typst-preview/src/actor/editor.rs
crates/typst-preview/src/actor/render.rs
crates/typst-preview/src/actor/webview.rs
crates/typst-preview/src/lib.rs

Since it is broken, we should check #1156 again carefully. @Enter-tainer

fix: clean up the render actor a bit and fix the issue that `editor_conn_sender` is not used

---

crates/tinymist-project/src/compiler.rs
crates/tinymist-vfs/src/lib.rs
crates/tinymist-world/src/source.rs
crates/tinymist-world/src/world.rs
crates/tinymist/src/project.rs
crates/tinymist/src/server.rs

close #763. Fixed some bugs that prevent good cache and detection.

feat: detect compilation-related vfs changes

---

crates/tinymist-project/src/font.rs

https://github.com/Myriad-Dreamin/tinymist/actions/runs/12878018507/job/35903350127

fix: try getting font index which is hit by comemo

---

editors/vscode/src/features/drag-and-drop.ts

and update rexllent package version to 0.3.0

feat: support drag-and-drop feature for .ods format

---

Cargo.lock

* build: lock `cc` version
* build: update cargo.lock
* docs: detailed comment
* build: remove the unneeded change
---------

build: update `cc` version (#1162)

---

crates/tinymist/src/tool/preview.rs

fix: respect that the port of the `expected_origin` can be zero

---

editors/vscode/Configuration.md
editors/vscode/package.json
editors/vscode/src/extension.shared.ts
editors/vscode/src/extension.ts
editors/vscode/src/extension.web.ts
editors/vscode/src/features/drop-paste.def.ts
editors/vscode/src/features/drop-paste.ts
editors/vscode/src/state.ts

The related vscode api is added in last month.

feat: add support to paste image into typst documents

---

crates/tinymist-vfs/src/lib.rs

* fix: invalid fs changes
* chore: print clean vfs state
* fix: increment revision in vfs correctly

fix: invalidate and increment revision in vfs correctly (#1292)

---

crates/tinymist-project/src/compiler.rs
crates/tinymist-world/src/snapshot.rs
crates/tinymist-world/src/world.rs
crates/tinymist/src/project.rs
crates/tinymist/src/tool/preview.rs

* fix: emit latest compiled artifact with correct signals
* fix: bad guard

fix: emit latest status and artifact with correct signals (#1294)

---

Cargo.lock
Cargo.toml
crates/tinymist/src/init.rs
editors/neovim/Configuration.md
editors/vscode/Configuration.md
editors/vscode/package.json

build: upgrade typstyle to v0.12.15

---

crates/tinymist/src/tool/preview.rs

Removed the port checking from the localhost and 127.0.0.1, CC @tmistele. This is unfortunately passing the origin from other clients from the localhost but does forbid the origin from external host like `huh.io`. I also added some quick tests to validate my code and thought.

fix: loose and test origin checking of the preview server

---

crates/tinymist/src/tool/preview.rs

* fix: loose and test origin checking of the preview server
* feat: check scheme
* feat: check expected origin without hacking

fix: loose and test origin checking of the preview server (#1353)

---

Cargo.lock
Cargo.toml
crates/tinymist-core/package.json
crates/tinymist/Cargo.toml
editors/vscode/CHANGELOG.md
editors/vscode/package.json
syntaxes/textmate/package.json

Note: this corresponding typst is v0.13.0.

build: bump version to 0.13.0-rc1

---

.github/workflows/release-vscode.yml

termux was broken by running completion in debug profile. Related issue:
- #1301

test(ci): add test about completion script generation

---

crates/tinymist/src/args.rs
crates/tinymist/src/init.rs
crates/tinymist/src/input.rs
crates/tinymist/src/lsp_query.rs
crates/tinymist/src/main.rs
crates/tinymist/src/resource/symbols.rs
crates/tinymist/src/server.rs
crates/tinymist/src/task/export.rs

To better understand or grep the code

refactor: specify type of trait method `Default::default`

---

editors/vscode/src/extension.shared.ts
editors/vscode/src/test/e2e/simple-docs.test.ts

Also added tests to avoid regression.

fix: deactivate features correctly when restarting server

---

editors/vscode/package.json
syntaxes/textmate/main.mts
syntaxes/textmate/tests/unit/markup/shebang-in-middle.typ
syntaxes/textmate/tests/unit/markup/shebang-in-middle.typ.snap
syntaxes/textmate/tests/unit/markup/shebang.typ
syntaxes/textmate/tests/unit/markup/shebang.typ.snap

Upstream related PR:
- https://github.com/typst/typst/pull/5702

feat: syntax highlight and filename association with shebang

---

crates/crityp/Cargo.toml

https://github.com/Myriad-Dreamin/tinymist/actions/runs/13538268001

feat: add `no-content-hint` feature to crityp

---

crates/tinymist-query/src/ty/builtin.rs

`TEST.PNG` is valid name of png image on windows.

feat: identify files ignoring cases

---

crates/tinymist/src/init.rs

https://github.com/WeetHet/typst.zed/issues/21#issuecomment-2601154723

feat: log update_by_map to debug zed configuration

---

tools/editor-tools/src/features/summary.ts

- skip `ArgSlots` if `serverInfos` is empty
- prints extra `ids` if `serverInfos.length > 1`
todo: pretty print information of all servers.

feat: improve `ArgSlots` a bit

---

editors/neovim/plugins/tinymist.lua

https://github.com/neovim/nvim-lspconfig/commit/e35fd81524b50bff187951253d4f6c9c97a7d013

feat: don't override `single_file_support` in tinymist.lua

---

crates/tinymist-world/src/compute.rs
crates/tinymist/src/task/export.rs

HTML export is allowed even if export target is set to paged since this PR, and vice versa.

feat: export to format regardless of export target

---

crates/tinymist-query/src/analysis/completion.rs
crates/tinymist-query/src/analysis/completion/field_access.rs
crates/tinymist-query/src/analysis/completion/scope.rs
crates/tinymist-query/src/analysis/completion/snippet.rs
crates/tinymist-query/src/analysis/completion/typst_specific.rs
crates/tinymist-query/src/fixtures/completion/dot_call_math.typ
crates/tinymist-query/src/fixtures/completion/dot_content_math.typ
crates/tinymist-query/src/fixtures/completion/dot_contextual_math.typ
crates/tinymist-query/src/fixtures/completion/dot_contextual_math2.typ
crates/tinymist-query/src/fixtures/completion/dot_contexual_math3.typ
crates/tinymist-query/src/fixtures/completion/dot_dict_math.typ
crates/tinymist-query/src/fixtures/completion/dot_element_math.typ
crates/tinymist-query/src/fixtures/completion/dot_element_math2.typ
crates/tinymist-query/src/fixtures/completion/dot_module_math.typ
crates/tinymist-query/src/fixtures/completion/dot_str_code.typ
crates/tinymist-query/src/fixtures/completion/dot_str_markup.typ
crates/tinymist-query/src/fixtures/completion/dot_str_math.typ
crates/tinymist-query/src/fixtures/completion/snaps/test@dot_call_math.typ.snap
crates/tinymist-query/src/fixtures/completion/snaps/test@dot_content_math.typ.snap
crates/tinymist-query/src/fixtures/completion/snaps/test@dot_contextual_math.typ.snap
crates/tinymist-query/src/fixtures/completion/snaps/test@dot_contextual_math2.typ.snap
crates/tinymist-query/src/fixtures/completion/snaps/test@dot_contexual_math3.typ.snap
crates/tinymist-query/src/fixtures/completion/snaps/test@dot_dict_math.typ.snap
crates/tinymist-query/src/fixtures/completion/snaps/test@dot_element_math.typ.snap
crates/tinymist-query/src/fixtures/completion/snaps/test@dot_element_math2.typ.snap
crates/tinymist-query/src/fixtures/completion/snaps/test@dot_module_math.typ.snap
crates/tinymist-query/src/fixtures/completion/snaps/test@dot_str_code.typ.snap
crates/tinymist-query/src/fixtures/completion/snaps/test@dot_str_markup.typ.snap
crates/tinymist-query/src/fixtures/completion/snaps/test@dot_str_math.typ.snap

See fixtures to learn the fixed syntaxes.

feat: forbid bad field access syntax in math mode

---

crates/tinymist/src/task/export.rs

feat: use atomic file writing for export

---

crates/tinymist-query/src/fixtures/jump_from_cursor/markup_text.typ
crates/tinymist-query/src/fixtures/jump_from_cursor/math_text.typ
crates/tinymist-query/src/fixtures/jump_from_cursor/snaps/test@markup_text.typ.snap
crates/tinymist-query/src/fixtures/jump_from_cursor/snaps/test@math_text.typ.snap
crates/tinymist-query/src/jump.rs
crates/tinymist-query/src/tests.rs

Since there was some stupid refactor, I also do some simple tests to examine it works on at least some simple documents.

fix: correct `jump_from_cursor` and add tests

---

tools/typst-preview-frontend/src/drag.ts

fix: allow drag preview horizontally

---

docs/tinymist/frontend/neovim.typ
editors/neovim/README.md

docs: Update Neovim config to use non-blocking system call

---

crates/tinymist-query/src/analysis/global.rs
crates/tinymist-task/src/compute.rs
crates/tinymist-world/src/snapshot.rs
crates/tinymist/src/config.rs
crates/tinymist/src/project.rs
editors/vscode/package.json
locales/tinymist-vscode.toml

https://github.com/Myriad-Dreamin/tinymist/blob/ff3127577b19621b90e02cec6dbb8ca0d2364aeb/editors/vscode/package.json#L370-L389

feat: allow to disable lint or lint on save

---

crates/tinymist-project/src/compiler.rs
crates/tinymist/src/actor/editor.rs
crates/tinymist/src/project.rs
editors/vscode/src/ui-extends.ts

feat: refactor and add page count for the status bar format

---

Cargo.lock
Cargo.toml
crates/tinymist-package/Cargo.toml
crates/tinymist-package/src/lib.rs
crates/tinymist-package/src/pack.rs
crates/tinymist-package/src/pack/fs.rs
crates/tinymist-package/src/pack/gitcl.rs
crates/tinymist-package/src/pack/http.rs
crates/tinymist-package/src/pack/memory.rs
crates/tinymist-package/src/pack/ops.rs
crates/tinymist-package/src/pack/release.rs
crates/tinymist-package/src/pack/tarball.rs
crates/tinymist-package/src/pack/universe.rs
crates/tinymist-package/src/registry.rs
crates/tinymist-package/src/registry/browser.rs
crates/tinymist-package/src/registry/dummy.rs
crates/tinymist-package/src/registry/http.rs
crates/tinymist-project/src/lsp.rs
crates/tinymist-query/src/package.rs
crates/tinymist-std/src/fs/paths.rs
crates/tinymist-world/Cargo.toml
crates/tinymist-world/src/browser.rs
crates/tinymist-world/src/package/mod.rs
crates/tinymist-world/src/system.rs

feat: extract package implementation

---

Cargo.lock
Cargo.toml
contrib/html/editors/vscode/package.json
crates/tinymist-core/package.json
crates/tinymist-derive/Cargo.toml
crates/tinymist-project/Cargo.toml
crates/tinymist-std/Cargo.toml
crates/tinymist-task/Cargo.toml
crates/tinymist-vfs/Cargo.toml
crates/tinymist-world/Cargo.toml
crates/typst-shim/Cargo.toml
editors/vscode/package.json
syntaxes/textmate/package.json

build: bump version to 0.13.12-rc4

---

crates/tinymist-world/src/font/resolver.rs

the bug fix was made in #1213 but discard in #1645, but this PR fix another potential oob access.

fix: try getting font index again (#1213, #1645)

---

Cargo.lock
Cargo.toml
crates/typlite/src/common.rs
crates/typlite/src/parser/core.rs
crates/typlite/src/parser/inline.rs
crates/typlite/src/parser/list.rs
crates/typlite/src/parser/media.rs
crates/typlite/src/parser/table.rs
crates/typlite/src/writer/docx/writer.rs
crates/typlite/src/writer/latex.rs

should merge https://github.com/Myriad-Dreamin/tinymist/pull/1812 first otherwise there will be merge conflicts.

refactor(typlite): use EcoString instead

---

docs/tinymist/frontend/helix.typ

im dumb and i didnt manage to config helix right so this might help other people too :3

docs: mention background preview in helix docs

---

docs/tinymist/book.typ
docs/tinymist/inputs.typ
docs/tinymist/module/lsp.typ

Following docs about https://github.com/Myriad-Dreamin/tinymist/issues/1725#issuecomment-2994804595

docs: update language server dev docs

---

crates/tinymist-task/src/compute/text.rs

This fix weird description in shiroa

feat: skip exporting style elements in HTML nodes

---

.github/workflows/build-vscode-others.yml

https://github.com/actions/runner/issues/801#issuecomment-2976165281

fix: alpine arm64 was not building

---

crates/tinymist-project/src/lsp.rs
crates/tinymist-tests/src/lib.rs
crates/tinymist/src/project.rs

feat: introduce dyn access model for futher development

---

crates/tinymist-project/src/lsp.rs
crates/tinymist/src/config.rs
crates/tinymist/src/input.rs
crates/tinymist/src/input/client.rs
crates/tinymist/src/project.rs
editors/vscode/src/extension.shared.ts
editors/vscode/src/lsp.ts
editors/vscode/src/util.ts

This is to avoid touching underlying file system if the extension is run with liveshare.

feat: implement delegate access model

---

.github/workflows/release-nightly.yml
Cargo.lock
Cargo.toml
crates/tinymist-analysis/src/upstream/mod.rs

+ several fixes to `nightly.yml`
+ update `comemo` for typst/typst#6683

dev: update nightly

---

Cargo.lock
Cargo.toml
contrib/html/editors/vscode/package.json
contrib/nix/dev/flake.nix
crates/tinymist-core/package.json
editors/neovim/bootstrap.sh
editors/neovim/samples/lazyvim-dev/Dockerfile
editors/vscode/CHANGELOG.md
editors/vscode/package.json
package.json
syntaxes/textmate/package.json

build: bump version to 0.13.20-rc1

---

.github/workflows/ci.yml

Reverts Myriad-Dreamin/tinymist#1962

revert: "fix(ci): detect create intead of push (#1962)"

---

Cargo.lock
Cargo.toml
contrib/html/editors/vscode/package.json
contrib/nix/dev/flake.nix
crates/tinymist-core/package.json
editors/neovim/bootstrap.sh
editors/neovim/samples/lazyvim-dev/Dockerfile
editors/vscode/CHANGELOG.md
editors/vscode/package.json
package.json
syntaxes/textmate/package.json

build: bump version to 0.13.22-rc1

---

Cargo.lock
Cargo.toml
contrib/html/editors/vscode/package.json
contrib/nix/dev/flake.nix
crates/tinymist-core/package.json
editors/neovim/bootstrap.sh
editors/neovim/samples/lazyvim-dev/Dockerfile
editors/vscode/CHANGELOG.md
editors/vscode/package.json
flake.lock
package.json
syntaxes/textmate/package.json

build: bump version to 0.13.22

---

crates/tinymist-analysis/src/syntax/matcher.rs
crates/tinymist-query/src/fixtures/rename/label.typ
crates/tinymist-query/src/fixtures/rename/label_indir.typ
crates/tinymist-query/src/fixtures/rename/label_indir2.typ
crates/tinymist-query/src/fixtures/rename/snaps/prepare@label.typ.snap
crates/tinymist-query/src/fixtures/rename/snaps/prepare@label_indir.typ.snap
crates/tinymist-query/src/fixtures/rename/snaps/prepare@label_indir2.typ.snap
crates/tinymist-query/src/fixtures/rename/snaps/test@label.typ.snap
crates/tinymist-query/src/fixtures/rename/snaps/test@label_indir.typ.snap
crates/tinymist-query/src/fixtures/rename/snaps/test@label_indir2.typ.snap
crates/tinymist-query/src/prepare_rename.rs
crates/tinymist-query/src/rename.rs
crates/tinymist-query/src/will_rename_files.rs

feat: rename labels

---

crates/typlite/README.md
docs/for-llm/neovim-ui.md
docs/for-llm/vscode-ui.md
docs/tinymist/frontend/common-finding-executable.typ
editors/emacs/README.md
editors/helix/README.md
editors/neovim/Configuration.md
editors/neovim/README.md
editors/vscode/Configuration.md

docs: update commands to install tinymist cli

---

docs/for-llm/neovim-ui.md
docs/for-llm/vscode-ui.md
editors/neovim/Configuration.md
editors/vscode/Configuration.md
locales/tinymist-vscode.toml

docs: remove `-` hint

---

Cargo.lock
Cargo.toml
contrib/html/editors/vscode/package.json
contrib/nix/dev/flake.nix
crates/tinymist-derive/Cargo.toml
crates/tinymist-l10n/Cargo.toml
crates/tinymist-package/Cargo.toml
crates/tinymist-project/Cargo.toml
crates/tinymist-std/Cargo.toml
crates/tinymist-task/Cargo.toml
crates/tinymist-vfs/Cargo.toml
crates/tinymist-world/Cargo.toml
crates/tinymist/package.json
crates/typst-shim/Cargo.toml
editors/neovim/bootstrap.sh
editors/neovim/samples/lazyvim-dev/Dockerfile
editors/vscode/package.json
package.json
syntaxes/textmate/package.json

build: bump version to 0.13.24-rc2

---

Cargo.lock
Cargo.toml
contrib/html/editors/vscode/package.json
contrib/nix/dev/flake.nix
crates/tinymist-derive/Cargo.toml
crates/tinymist-l10n/Cargo.toml
crates/tinymist-package/Cargo.toml
crates/tinymist-project/Cargo.toml
crates/tinymist-std/Cargo.toml
crates/tinymist-task/Cargo.toml
crates/tinymist-vfs/Cargo.toml
crates/tinymist-world/Cargo.toml
crates/tinymist/package.json
crates/typst-shim/Cargo.toml
editors/neovim/bootstrap.sh
editors/neovim/samples/lazyvim-dev/Dockerfile
editors/vscode/package.json
package.json
syntaxes/textmate/package.json

build: bump version to 0.13.24-rc3

---

Cargo.lock
Cargo.toml
contrib/html/editors/vscode/package.json
contrib/nix/dev/flake.nix
crates/tinymist-derive/Cargo.toml
crates/tinymist-l10n/Cargo.toml
crates/tinymist-package/Cargo.toml
crates/tinymist-project/Cargo.toml
crates/tinymist-std/Cargo.toml
crates/tinymist-task/Cargo.toml
crates/tinymist-vfs/Cargo.toml
crates/tinymist-world/Cargo.toml
crates/tinymist/package.json
crates/typst-shim/Cargo.toml
editors/neovim/bootstrap.sh
editors/neovim/samples/lazyvim-dev/Dockerfile
editors/vscode/CHANGELOG.md
editors/vscode/package.json
package.json
syntaxes/textmate/package.json

build: bump version to 0.13.24

---

Cargo.lock
Cargo.toml
contrib/html/editors/vscode/package.json
contrib/nix/dev/flake.nix
crates/tinymist/package.json
editors/neovim/bootstrap.sh
editors/neovim/samples/lazyvim-dev/Dockerfile
editors/vscode/package.json
package.json
scripts/release.mjs
syntaxes/textmate/package.json

build: bump version to 0.13.26

---

Cargo.lock
Cargo.toml
contrib/html/editors/vscode/package.json
contrib/nix/dev/flake.nix
crates/tinymist/package.json
editors/neovim/bootstrap.sh
editors/neovim/samples/lazyvim-dev/Dockerfile
editors/vscode/package.json
package.json
syntaxes/textmate/package.json

build: bump version to 0.13.28-rc2
