- editors/vscode/src/extension.ts
to remove diagnostics when you change to other kind of files, for example, some rust file.
> dev: unfocus document on changed to other files

- README.md
- crates/tinymist-query/src/analysis/def_use.rs
- crates/tinymist-query/src/analysis/global.rs
- crates/tinymist-query/src/analysis/lexical_hierarchy.rs
- crates/tinymist-query/src/fixtures/references/cross_module.typ
- crates/tinymist-query/src/fixtures/references/cross_module2.typ
- crates/tinymist-query/src/fixtures/references/cross_module_absolute.typ
- crates/tinymist-query/src/fixtures/references/cross_module_alias.typ
- crates/tinymist-query/src/fixtures/references/cross_module_alias2.typ
- crates/tinymist-query/src/fixtures/references/cross_module_relative.typ
- crates/tinymist-query/src/fixtures/references/snaps/test@cross_module.typ.snap
- crates/tinymist-query/src/fixtures/references/snaps/test@cross_module2.typ.snap
- crates/tinymist-query/src/fixtures/references/snaps/test@cross_module_absolute.typ.snap
- crates/tinymist-query/src/fixtures/references/snaps/test@cross_module_alias.typ.snap
- crates/tinymist-query/src/fixtures/references/snaps/test@cross_module_alias2.typ.snap
- crates/tinymist-query/src/fixtures/references/snaps/test@cross_module_relative.typ.snap
- crates/tinymist-query/src/inlay_hint.rs
- crates/tinymist-query/src/references.rs
- crates/tinymist/src/actor/typst.rs
[References](https://code.visualstudio.com/api/language-extensions/programmatic-language-features#find-all-references-to-a-symbol)
- Right-click on a symbol and select "Go to References" or "Find References".
- Or ctrl+click on a symbol.
> feat: support query of cross-module references

- .github/workflows/release.yml
- editors/vscode/.eslintrc.js
- editors/vscode/package.json
- editors/vscode/scripts/postinstall.cjs
- editors/vscode/src/editor-tools.ts
- editors/vscode/src/extension.ts
- editors/vscode/tsconfig.json
- package.json
- tools/editor-tools/.gitignore
- tools/editor-tools/index.html
- tools/editor-tools/package.json
- tools/editor-tools/src/global.d.ts
- tools/editor-tools/src/main.ts
- tools/editor-tools/src/style.css
- tools/editor-tools/src/vscode.ts
- tools/editor-tools/tsconfig.json
- tools/editor-tools/vite.config.js
- yarn.lock
add a `tinymist.showTemplateGallery` command for starting the template gallery tool.
> feat: add template gallery as template picker

- crates/tinymist/src/init.rs
- crates/tinymist/src/lib.rs
- editors/vscode/src/extension.ts
- editors/vscode/src/vscode-variables.d.ts
- tools/editor-tools/src/global.d.ts
You can set root/server/font path(s) with vscode variables. The variables are listed in https://www.npmjs.com/package/vscode-variables.
+ more testing and validation
> feat: supports vscode variables in configurations and ..

- Cargo.lock
- crates/tinymist/Cargo.toml
- crates/tinymist/README.md
- crates/tinymist/src/main.rs
You can build the program with `dhat-heap` feature to collect memory usage with DHAT. The DHAT will instrument the allocator dynamically, so it will slow down the program significantly.
```sh
cargo build --release --bin tinymist --features dhat-heap
```
The instrumented program is nothing different from the normal program, so you can mine the specific memory usage with a lsp session (recorded with `--mirror`) by replaying the input.
```sh
./target/release/tinymist --replay input.txt
...
dhat: Total:     740,668,176 bytes in 1,646,987 blocks
dhat: At t-gmax: 264,604,009 bytes in 317,241 blocks
dhat: At t-end:  259,597,420 bytes in 313,588 blocks
dhat: The data has been saved to dhat-heap.json, and is viewable with dhat/dh_view.html
```
Once you have the `dhat-heap.json`, you can visualize …
> feat: provide dhat instrumenting feature for heap usage analysis

- crates/tinymist/src/actor/compile.rs
- crates/tinymist/src/actor/typst.rs
> fix: steal the latest compiled document for lsp functions

- Cargo.lock
- crates/tinymist/src/server/lsp.rs
- crates/tinymist/src/server/lsp_init.rs
- crates/tinymist/src/state.rs
- tests/Cargo.toml
Previously we run two instances if users or typst-preview request pinning, which is not optimal. Now we can gracefully run with a single compiler instance. The dedicate-compiler design is still reserved for concurrent task in future.
> dev: ensure to run a single compiler instance

- Cargo.lock
- crates/tinymist-query/Cargo.toml
- crates/tinymist-query/src/diagnostics.rs
- crates/tinymist-query/src/goto_declaration.rs
- crates/tinymist-query/src/goto_definition.rs
- crates/tinymist-query/src/lsp_typst_boundary.rs
- crates/tinymist-query/src/prelude.rs
- crates/tinymist-query/src/references.rs
- crates/tinymist-query/src/rename.rs
- crates/tinymist-query/src/symbol.rs
- crates/tinymist/src/actor/render.rs
- crates/tinymist/src/actor/typ_client.rs
- crates/tinymist/src/server/compiler.rs
- crates/tinymist/src/server/compiler_init.rs
- crates/tinymist/src/server/lsp.rs
- crates/tinymist/src/state.rs
- editors/vscode/src/extension.ts
VSCode uses untitled scheme to mark unsaved text buffer that not yet synchronized to disk.
> feat: support untitled url scheme for unsaved text buffer

- crates/tinymist/src/actor.rs
- crates/tinymist/src/actor/typ_client.rs
- crates/tinymist/src/main.rs
- crates/tinymist/src/server/compiler.rs
- crates/tinymist/src/server/compiler_init.rs
- crates/tinymist/src/server/lsp.rs
- crates/tinymist/src/server/lsp_init.rs
- crates/tinymist/src/state.rs
support it by a `CompileExtraOpts` that applied in low priority. An entry configuration could be overridden by dynamic pinning command.
```rs
#[derive(Debug, Clone, PartialEq, Default)]
pub struct CompileExtraOpts {
/// The root directory for compilation routine.
pub root_dir: Option<PathBuf>,
/// Path to entry
pub entry: Option<ImmutPath>,
/// Additional input arguments to compile the entry file.
pub inputs: ImmutDict,
/// will remove later
pub font_paths: Vec<PathBuf>,
}
```
The `CompileExtraOpts` is purposed for allowing users specify arguments for lsp like what they do for `typst-cli`. The `CompileExtraOpts` is easy to use but error-prone, so it is applied in low priority.
Example for VSCode:
```jsonc
{
"tinymist.typstExtraArgs": [
// specify sys.inputs
"--input=theme=dark", …
```
> feat: support entry configuration

- crates/tinymist/src/actor/typ_client.rs
- crates/tinymist/src/actor/typ_server.rs
Reverts Myriad-Dreamin/tinymist#161
It helps reduce memory consumption a bit but causes thrashing use of cache.
> revert: "dev: evict cache more frequently"

- Cargo.lock
- Cargo.toml
I mark this pr as draft in case of there is another version before tinymist's next release
Changelog: https://github.com/Enter-tainer/typstyle/releases/tag/v0.11.13
> chore: bump typstyle to v0.11.13

- crates/tinymist-query/src/analysis/linked_def.rs
- crates/tinymist-query/src/inlay_hint.rs
Since this PR, the overhead of overall analysis to expression definitions is off-loaded by static analysis.
> dev: prefer less uses of `analzer_expr` during definition analysis

- Cargo.lock
- Cargo.toml
- crates/tinymist/src/actor/formatting.rs
Bump typstyle v0.11.14 and use `Source` based API to avoid re-parsing
> chore: bump to typstyle v0.11.14

- Cargo.lock
- Cargo.toml
- editors/vscode/CHANGELOG.md
- editors/vscode/package.json
- syntaxes/textmate/package.json
- tools/editor-tools/src/features/summary.ts
* Fixed wrong check of param completion position at comma in https://github.com/Myriad-Dreamin/tinymist/pull/205
* Completing text.lang/region in https://github.com/Myriad-Dreamin/tinymist/pull/199
* Completing array/tuple literals in https://github.com/Myriad-Dreamin/tinymist/pull/201
* New array types completed: columns/ros/gutter/column-gutter/row-gutter/size/dash on various functions
* Completing function arguments on signatures inferred by type checking in https://github.com/Myriad-Dreamin/tinymist/pull/203
* Completing function arguments of func.where and func.with by its method target (this) in https://github.com/Myriad-Dreamin/tinymist/pull/204
* Completing functions with where/with snippets in https://github.com/Myriad-Dreamin/tinymist/pull/206
* Checking variadic/content …
> build: bump version to 0.11.5

- Cargo.lock
- Cargo.toml
- README.md
- editors/vscode/CHANGELOG.md
- editors/vscode/README.md
- editors/vscode/package.json
- syntaxes/textmate/package.json
- tools/editor-tools/src/features/summary.ts
* Added more auto closing pairs, surrounding pairs, and characters that could make auto closing before in https://github.com/Myriad-Dreamin/tinymist/pull/209
* Hiding Status bar until the recent focus file is closed in https://github.com/Myriad-Dreamin/tinymist/pull/212
* (Fix) Removed a stupid debugging which may cause panic in https://github.com/Myriad-Dreamin/tinymist/pull/215
* Completed symbol view in https://github.com/Myriad-Dreamin/tinymist/pull/218
* Not all symbols are categorized yet. If not, they are put into the "Misc" category.
* It is now showing in the activity bar (sidebar). Feel free to report any issues or suggestions for improvement.
**Full Changelog**: https://github.com/Myriad-Dreamin/tinymist/compare/v0.11.5...v0.11.6
> build: bump version to 0.11.6

- editors/vscode/package.json
Hide activity bar icon when res lang id is not typst
see 
- https://github.com/Enter-tainer/typst-preview/pull/288
- https://github.com/microsoft/vscode/issues/49145
> feat: conditionally open activity icon when lang id is typst

- editors/vscode/package.json
Enable it if you would like to have it:
```json
{
"[typst]": {
"editor.inlayHints.enabled": "on"
}
}
```
> feat: disable inlay hints

- Cargo.lock
- Cargo.toml
- editors/vscode/CHANGELOG.md
- editors/vscode/package.json
- syntaxes/textmate/package.json
* Improved open document tooltip in https://github.com/Myriad-Dreamin/tinymist/pull/254
* Inserting commas in argument context for completing before identifiers in https://github.com/Myriad-Dreamin/tinymist/pull/251
* Improved identifying literal expressions in https://github.com/Myriad-Dreamin/tinymist/pull/252
* Identifying let context completely in https://github.com/Myriad-Dreamin/tinymist/pull/255
* To help complete after equal marker in `let b = ..`
* Restoring left parenthesis and comma as trigger characters in https://github.com/Myriad-Dreamin/tinymist/pull/253
* This is needed for completion on literal expressions.
* (Fix) Avoiding infinite loop in simplifying recursive functions in https://github.com/Myriad-Dreamin/tinymist/pull/246
* Fix a stack overflow in `ty.rs`
* (Fix) …
> build: bump version to 0.11.8

- crates/tinymist/src/actor/typ_client.rs
- crates/tinymist/src/server/lsp.rs
- crates/tinymist/src/state.rs
> After opening the file it doesn't show the error unless I save the file (no-op).
> > vscode invokes lsp's focus command but neovim doesn't. should add an issue, and discuss a suitable behavior to change focus file if the client is neovim.
It is nice if client focus entry explicitly, however neovim/helix/zed clients don't do that. Adding many activity hooks to track activating document status if a client is not performing any focus command request.
We do want to focus the file implicitly by `textDocument/diagnostic` (pullDiagnostics mode), as suggested by language-server-protocol#718, however, this has poor support, e.g. since neovim 0.10.0.
See https://github.com/microsoft/language-server-protocol/issues/718
> feat: implicitly focus entry on no focus request sent

- crates/tinymist-query/src/lsp_typst_boundary.rs
- crates/tinymist-query/src/semantic_tokens/mod.rs
- crates/tinymist/src/actor/export.rs
- crates/tinymist/src/actor/typ_client.rs
- crates/tinymist/src/lib.rs
The `byte_to_line` api will panic if the offset equals to the length in bytes.
> fix: handle the conversion of offset at the EOF

- Cargo.lock
- Cargo.toml
changelog: https://enter-tainer.github.io/typstyle/changelog/#v01123---2024-05-25
table formatting enhancement
> chore: bump typstyle to v0.11.26

- Cargo.lock
- Cargo.toml
- editors/vscode/CHANGELOG.md
- editors/vscode/package.json
- syntaxes/textmate/package.json
* Bumped typstyle to v0.11.26 by @Enter-tainer in https://github.com/Myriad-Dreamin/tinymist/pull/326
* (Fix): Handling the conversion of offset at the EOF in https://github.com/Myriad-Dreamin/tinymist/pull/325
* (Fix) Accumulating export events correctly in https://github.com/Myriad-Dreamin/tinymist/pull/330
* Highlighting all break points for that loop context in https://github.com/Myriad-Dreamin/tinymist/pull/317
* Implemented `experimental/onEnter` in https://github.com/Myriad-Dreamin/tinymist/pull/328
* Generating names for destructuring closure params by @wrenger in https://github.com/Myriad-Dreamin/tinymist/pull/319
* Combined CompileClient and CompileClientActor by @QuarticCat in https://github.com/Myriad-Dreamin/tinymist/pull/318
* Simplified pin_entry by @QuarticCat in …
> build: bump version to 0.11.11

- editors/vscode/package.json
- editors/vscode/src/editor-tools.ts
- tools/editor-tools/package.json
- tools/editor-tools/src/features/summary.ts
- tools/editor-tools/src/icons.ts
- tools/editor-tools/src/style.css
- tools/editor-tools/src/vscode.ts
- yarn.lock
This PR adds a "Copy" icon to the top right corner of the font list card, in the VSCode extension's summary page:
Clicking it opens a font list export panel, which can export the list of fonts  as plain text:
By default, only the paths of external font files are exported.
The options above can control whether to include Typst built-in fonts and whether to add extra information such as font names:
Click the "Copy" button at the bottom to perform the copy.
---
This feature fully from a personal need of mine. Upon discovering that tinymist already had a feature of showing document font lists, I think implement it here may save my coding time(And it's true).
If the author also finds this feature useful, I am more than happy to polish the code based on review comments.
If you feel this feature …
> feat: add font list export panel in summary tool

- Cargo.lock
- Cargo.toml
- editors/vscode/CHANGELOG.md
- editors/vscode/package.json
- scripts/publish.ps1
- syntaxes/textmate/package.json
- tools/typst-dom/package.json
- tools/typst-preview-frontend/package.json
- yarn.lock
@Enter-tainer, `preview` command is now available by command, meaning that we are ready for replacing binary:
>* Moved typst-preview to tinymist and combined the binary and compiler in https://github.com/Myriad-Dreamin/tinymist/pull/323, https://github.com/Myriad-Dreamin/tinymist/pull/332, and https://github.com/Myriad-Dreamin/tinymist/pull/337
```bash
cargo run --bin tinymist -- preview main.typ
```
**Note:** However, the built typst-preview extension is not tested. We can do it in next round of developing.
---
* Bumped typstyle to v0.11.28
* Added base documentation website in https://github.com/Myriad-Dreamin/tinymist/pull/344 and https://github.com/Myriad-Dreamin/tinymist/pull/345
* Preparing for parallelizing lsp requests in https://github.com/Myriad-Dreamin/tinymist/pull/342
* Added …
> build: bump version to 0.11.12

- .github/workflows/release.yml
`macos-11` runner is removed in GitHub Q3. See https://github.com/actions/runner-images/issues/9255.
> feat(ci): upgrade macos runner

- editors/neovim/Configuration.md
- editors/vscode/Configuration.md
- editors/vscode/package.json
- editors/vscode/src/extension.ts
- editors/vscode/src/preview.ts
- Added a configuration to turn on/off preview feature globally.
- Changed the configuration items in tinymist extension's `package.json` now, as I find vscode will warn conflict items when both typst-preview and tinymist extension are installed and enabed.
- Changed the name of components as well.
> feat: full compatible with typst-preview extension

- Cargo.lock
- Cargo.toml
- contrib/typst-preview/editors/vscode/CHANGELOG.md
- contrib/typst-preview/editors/vscode/package.json
- editors/vscode/CHANGELOG.md
- editors/vscode/package.json
- syntaxes/textmate/package.json
This bug is introduced by [Preparing for parallelizing lsp requests](https://github.com/Myriad-Dreamin/tinymist/pull/342).
* (Fix) Lsp should respond errors at tail in https://github.com/Myriad-Dreamin/tinymist/pull/367
* Supported single-task preview commands in https://github.com/Myriad-Dreamin/tinymist/pull/364, https://github.com/Myriad-Dreamin/tinymist/pull/368, https://github.com/Myriad-Dreamin/tinymist/pull/370, and https://github.com/Myriad-Dreamin/tinymist/pull/371
* Typst Preview extension is already integrated into Tinymist. It . Please disable Typst Preview extension to avoid conflicts.
* Otherwise, you should disable the tinymist's embedded preview feature by `"tinymist.preview": "disable"` in your settings.json.
* Persisting webview preview through vscode restarts by …
> build: bump version to 0.11.14

- crates/tinymist/src/actor/typ_server.rs
- crates/tinymist/src/lib.rs
- crates/tinymist/src/main.rs
- crates/tinymist/src/server.rs
Let `R` be the marker of revision-changed events, `S` be the snapshot events, and `O` be others. The sequence of user triggering events usually have the snapshot:
```
`R`, `S`,  `S`,  `S`, `S`, `S`, `R`, `S`, `R`, `S`, `R`, `O`
```
In short the client usually changes the state and follows many state queries.
This will prevent optimization about the event accumulation since current `COMPILE_CONCURRENCY` is `0` and we cannot combine `R`s if there is any `S` between them.
The correct fix is to increase `COMPILE_CONCURRENCY` but I find it not very trivial. For example, if they hit keyboard fast, one's machine may be overwhelmed with compilation threads and cause poor performance (when most of you cpus are used for compilations and analysis tasks will cry) and power efficiency.
---
To fix it …
> feat: allow deferred snapshot event processing

- Cargo.lock
- Cargo.toml
This version improves dot chain format. Changelog: https://enter-tainer.github.io/typstyle/changelog/#v01129---2024-07-13
> build: bump typstyle to v0.11.29

- Cargo.lock
- Cargo.toml
This version fix a critical bug that exists since typstyle's first release. https://enter-tainer.github.io/typstyle/changelog/#v01130---2024-07-14
> build: bump typstyle to v0.11.30

- Cargo.lock
- Cargo.toml
- editors/vscode/CHANGELOG.md
- editors/vscode/package.json
- syntaxes/textmate/package.json
* Bumped typstyle to v0.11.30 by @Enter-tainer in https://github.com/Myriad-Dreamin/tinymist/pull/416
* (Fix) Noting `formatter_print_width` change on changed configuration in https://github.com/Myriad-Dreamin/tinymist/pull/387
* Keeping entry on language query in https://github.com/Myriad-Dreamin/tinymist/pull/406
* Allowed deferred snapshot event processing in https://github.com/Myriad-Dreamin/tinymist/pull/408
* (Fix) Showing views in activity bar whenever the extension is activated in https://github.com/Myriad-Dreamin/tinymist/pull/414
* Rendering example code in typst docs as typst syntax in https://github.com/Myriad-Dreamin/tinymist/pull/397
* Using `requestIdleCallback` to wait for updating canvas pages when editor is in idle in https://github.com/Myriad-Dreamin/tinymist/pull/412
* …
> build: bump version to 0.11.15

- editors/vscode/package.json
Currently there are 5 descriptions and 4 values, so they do not match (e.g. when hovering the value in VS Code settings). This removes the "recommended" description, as the value does not seem to exist.
> fix: description for exportPdf setting

- crates/tinymist/src/actor/mod.rs
- crates/tinymist/src/actor/preview.rs
- crates/tinymist/src/actor/typ_client.rs
- crates/tinymist/src/cmd.rs
- crates/tinymist/src/server.rs
- crates/tinymist/src/tool/preview.rs
- crates/typst-preview/src/actor/render.rs
- crates/typst-preview/src/lib.rs
- editors/vscode/src/extension.ts
- editors/vscode/src/lsp.ts
- editors/vscode/src/preview-compat.ts
- editors/vscode/src/preview.ts
Previous PRs:
- #368
- #364 
- #337
- #332 
- #323 
--- 
Introducing dedicate servers that handle compilations and send diagnostics. The LSP will still always respond LSP requests according to the primary server's compilations.
Problem:
- It is not intuitive to distinguish primary preview instance and other instances. We need to merge lsp responses according to multiple instances.
- make `comemo::evict` work correctly on multiple compilers.
- we should improve performance on multiple instances.
> feat: allow multiple-tasked preview

- crates/tinymist/src/main.rs
I was simply bothered by how the program just panicked if I did not include a path in the compile command, so i replaced the unwrap with a match statement.
**before:**
**after:**
> Fix: Handling unwrap for the args in compile command

- crates/tinymist/src/tool/preview.rs
Resolves #463 
Disclaimer: these are my first lines of Rust ever.  It appears to work.
Thanks for having a straightforward `CONTRIBUTING.md` file.  I ran `./scripts/e2e.sh` successfully.  At first, `cargo insta` failed, but I figured out what it was and installed it.  A link to [cargo-insta](https://crates.io/crates/cargo-insta) might help other first-timers.
> fix: Modifies static host to send Content-Type: text/html

- Cargo.lock
- Cargo.toml
- crates/tinymist-query/src/analysis/linked_def.rs
- crates/tinymist-query/src/analysis/signature.rs
- crates/tinymist-query/src/upstream/complete/ext.rs
cherry pick https://github.com/typst/typst/pull/4300 to fix oftenly unstable snapshot testing since making LSP concurrent recently, for example https://github.com/Myriad-Dreamin/tinymist/actions/runs/10106214833/attempts/1.
> build: cherry pick concurrent id error

- crates/tinymist-query/src/completion.rs
- crates/tinymist-query/src/fixtures/completion/completion_title.typ
- crates/tinymist-query/src/fixtures/completion/completion_title2.typ
- crates/tinymist-query/src/fixtures/completion/completion_title3.typ
- crates/tinymist-query/src/fixtures/completion/snaps/test@completion_title.typ.snap
- crates/tinymist-query/src/fixtures/completion/snaps/test@completion_title2.typ.snap
- crates/tinymist-query/src/fixtures/completion/snaps/test@completion_title3.typ.snap
- crates/tinymist-query/src/upstream/complete.rs
When `at` is presented, open/close is neglected, thus the `apply` field is not correctly constructed.
A fix for https://github.com/Myriad-Dreamin/tinymist/issues/483
> fix: apply label instead of bib title name in `at` completion

- editors/vscode/src/test/e2e/index.ts
- editors/vscode/src/ui-extends.ts
Previously, zero items would use the singular noun (e.g. "0 Word"). However, zero should also be followed by a plural (i.e. only 1 is followed by a singular). This PR fixes that.
> fix: use plural for 0 items

- crates/tinymist/src/args.rs
- crates/tinymist/src/main.rs
I saw `clap_complete` is in Cargo.toml, but did not see it's usage, so I created a simple completion subcommand with it. Feel free to remove it if it's redundant work.
---
我看依赖里有`clap_complete`但是好像没有实现shell补全，就随便写了一个。假如其实已经有了就把这个issue 关了好了。
> feat: generate shell completion

- crates/typlite/Cargo.toml
- crates/typlite/src/lib.rs
- crates/typlite/src/tests.rs
A very basic fix for #531 , this fix just remove the feature `texmath` as the defualt implementation is good enough and `texmath` is not implemented
> fix: remove feature texmath

- editors/vscode/package.json
These features can still be hidden by vscode's owned separated flags.
> feat: remove useless `tinymist.preview.showInActivityBar`

- Cargo.lock
- Cargo.toml
https://enter-tainer.github.io/typstyle/changelog/#v01132---2024-08-19
> chore: bump typstyle to v0.11.32

- Cargo.lock
- Cargo.toml
- crates/tinymist-query/Cargo.toml
- crates/tinymist-query/src/analysis/signature.rs
- crates/tinymist-query/src/syntax/lexical_hierarchy.rs
- crates/tinymist-query/src/upstream/complete.rs
- crates/tinymist-query/src/upstream/tooltip.rs
- crates/tinymist/Cargo.toml
- crates/tinymist/src/actor/typ_server.rs
- crates/tinymist/src/init.rs
- crates/typlite/src/tests.rs
- crates/typst-shim/Cargo.toml
- crates/typst-shim/src/lib.rs
- crates/typst-shim/src/nightly/mod.rs
- crates/typst-shim/src/nightly/utils.rs
- crates/typst-shim/src/stable/mod.rs
- crates/typst-shim/src/stable/utils.rs
This PR introduces a compatibility layer to support both the stable and nightly versions of the Typst API. 
As an example, the `util` module in the stable version and the `utils` module in the nightly version have been unified under a single `utils` module in this crate. The correct API is chosen based on the feature flag (`nightly` or default).
> feat: Add compatibility layer for Typst stable and nightly APIs

- editors/vscode/src/gitpod.ts
- editors/vscode/src/preview.ts
- tools/typst-preview-frontend/src/main.js
Closes #382
Hi, thank you for this fantastic project.
Following the resolution of issue #382, I continued to investigate Tinymist on Gitpod. During my investigation, I discovered that Gitpod exposes local ports as subdomains of the workspace,
for example, `www.example.com:8000` is mapped to `8000-www.example.com`.
This pull request adds a translation layer for the Typst preview URLs to accommodate this behavior.
> feat: add gitpod layer

- crates/tinymist-query/src/analysis.rs
- crates/tinymist-query/src/analysis/global.rs
- crates/tinymist-query/src/analysis/import.rs
- crates/tinymist-query/src/analysis/linked_def.rs
- crates/tinymist-query/src/analysis/signature.rs
- crates/tinymist-query/src/code_action.rs
- crates/tinymist-query/src/code_context.rs
- crates/tinymist-query/src/document_highlight.rs
- crates/tinymist-query/src/hover.rs
- crates/tinymist-query/src/jump.rs
- crates/tinymist-query/src/on_enter.rs
- crates/tinymist-query/src/selection_range.rs
- crates/tinymist-query/src/signature_help.rs
- crates/tinymist-query/src/syntax/comment.rs
- crates/tinymist-query/src/syntax/matcher.rs
- crates/tinymist-query/src/tests.rs
- crates/tinymist-query/src/upstream/complete.rs
- crates/tinymist-query/src/upstream/tooltip.rs
- crates/tinymist/src/tool/preview.rs
- crates/typst-shim/src/nightly/mod.rs
- crates/typst-shim/src/nightly/syntax.rs
- crates/typst-shim/src/stable/mod.rs
- crates/typst-shim/src/stable/syntax.rs
Add compatibility for `typst_syntax::LinkedNode.leaf_at`
> refactor: add compatibility for `typst_syntax::LinkedNode.leaf_at`

- Cargo.lock
- Cargo.toml
- crates/tinymist-world/Cargo.toml
- editors/vscode/CHANGELOG.md
This is a new release channel for Tinymist, which uses *main branch of typst*. Currently it is only available at [nightly branch,](https://github.com/Myriad-Dreamin/tinymist/tree/nightly), but we will set up nightly release in soon future.
* Added compatibility layer for Typst stable and nightly APIs by @ParaN3xus in https://github.com/Myriad-Dreamin/tinymist/pull/573
* Added compatibility for `typst_syntax::LinkedNode.leaf_at` by @ParaN3xus in https://github.com/Myriad-Dreamin/tinymist/pull/582
* (Fix) Deadlock when iterating dependencies in https://github.com/Myriad-Dreamin/tinymist/pull/568
* This could happen when you are triggering workspace-level requests, like `symbol` or `reference` requests.
* (Fix) Ignoring system fonts correctly in …
> build: bump version to 0.11.22-rc1

- contrib/typlite/Cargo.toml
- defaulting to the 2015 edition while the latest is 2021
> fix: warning no edition set

- Cargo.lock
- Cargo.toml
- crates/tinymist-query/src/analysis/linked_def.rs
- crates/tinymist-query/src/fixtures/goto_definition/label_indir.typ
- crates/tinymist-query/src/fixtures/goto_definition/label_indir2.typ
- crates/tinymist-query/src/fixtures/goto_definition/snaps/test@label.typ.snap
- crates/tinymist-query/src/fixtures/goto_definition/snaps/test@label_indir.typ.snap
- crates/tinymist-query/src/fixtures/goto_definition/snaps/test@label_indir2.typ.snap
We get the labelled element by the introspector dynamically, and it is impossible to perform any further static analysis. Thus, unfortunately, this feature *MUST* have a typst patch that helps record the span where the label is attached. The patch deserves  further discussion on the official typst channel.
> feat: record and use span where the label is attached

- Cargo.lock
- Cargo.toml
- tests/e2e/main.rs
This version is at [build: bump node version to 22 (#654)](https://github.com/Myriad-Dreamin/tinymist/commits/f5520691fa3ff8ed7ecaf697d1908500534b39b0), using [ParaN3xus/typst tinymist-typst-0.12-rc1](https://github.com/ParaN3xus/typst/tree/tinymist-typst-0.12-rc1), a.k.a. [typst/typst v0.12.0-rc1](https://github.com/typst/typst/commits/v0.12.0-rc1).
> dev: nightly 0.11.33

- crates/tinymist-world/src/https.rs
- crates/tinymist-world/src/lib.rs
- crates/tinymist/src/args.rs
- crates/tinymist/src/cmd.rs
- crates/tinymist/src/main.rs
- crates/tinymist/src/server.rs
Intel vtune says `dirs::data_dir` and `dirs::cache_dir` make syscall on windows for each check existence of package files. This is a disaster on large packages.
With caching, the time used of `tinymist query packageDocs --id @preview/cetz:0.2.2` goes down from 0.9s to 0.7s.
Intel vtune also says `sys::stat` syscall takes 0.2s to check existence of package files, but this need more careful cache strategy.
Though we currently don't response changes of these two cached directory paths, it is less likely to be changed in application wide.
> feat: cache `dirs::data_dir` and `dirs::cache_dir`

- crates/tinymist/src/args.rs
- crates/tinymist/src/cmd.rs
- crates/tinymist/src/lib.rs
- crates/tinymist/src/main.rs
- crates/tinymist/src/task/user_action.rs
- tools/editor-tools/src/features/tracing.ts
> feat: send trace data via http instead of lsp stdio

- Cargo.lock
- Cargo.toml
- editors/vscode/CHANGELOG.md
- editors/vscode/package.json
- syntaxes/textmate/package.json
Note the real revision used by `v0.11.32` is [here](https://github.com/Myriad-Dreamin/tinymist/commits/v0.11.32), which is only a republish of `v0.11.28`.
> build: bump version to 0.11.32

- docs/tinymist/frontend/neovim.typ
- editors/neovim/README.md
This adds a simple example about how to config tinymist for coc.nvim users. Coc.nvim provides LSP support and is quite popular among both vim and, even after the builtin LSP support, nvim users. Having a coc section can be helpful to them.
> docs: add coc.nvim config example

- crates/tinymist-query/src/completion.rs
- crates/tinymist-query/src/upstream/complete.rs
- crates/tinymist-query/src/upstream/complete/ext.rs
- crates/tinymist/src/init.rs
- crates/tinymist/src/server.rs
- editors/vscode/src/extension.ts
- tests/e2e/main.rs
- tests/fixtures/initialization/vscode-1.87.2.json
Add three internal options to indicate whether to issue:
- `editor.action.triggerSuggest`
- `editor.action.triggerParameterHints`
- `tinymist.triggerNamedCompletion`
Here are the corresponding configuration items:
```rs
struct Config {
/// Whether to trigger suggest completion, a.k.a. auto-completion.
pub trigger_suggest: bool,
/// Whether to trigger parameter hint, a.k.a. signature help.
pub trigger_parameter_hints: bool,
/// Whether to trigger named parameter completion.
pub trigger_named_completion: bool,
}
```
They won't be exposed as user configuration but only in initialization options. The lsp clients (editor plugins or extensions) must take responsibility to probe related commands and fill these items with true or false. Otherwise, tinymist won't set these commands to completion …
> feat: client-side control to whether issue completion callback

- crates/tinymist-query/src/completion.rs
- crates/tinymist-query/src/fixtures/completion/colon_markup.typ
- crates/tinymist-query/src/fixtures/completion/colon_markup2.typ
- crates/tinymist-query/src/fixtures/completion/colon_math.typ
- crates/tinymist-query/src/fixtures/completion/colon_math2.typ
- crates/tinymist-query/src/fixtures/completion/colon_param.typ
- crates/tinymist-query/src/fixtures/completion/snaps/test@colon_markup.typ.snap
- crates/tinymist-query/src/fixtures/completion/snaps/test@colon_markup2.typ.snap
- crates/tinymist-query/src/fixtures/completion/snaps/test@colon_math.typ.snap
- crates/tinymist-query/src/fixtures/completion/snaps/test@colon_math2.typ.snap
- crates/tinymist-query/src/fixtures/completion/snaps/test@colon_param.typ.snap
- crates/tinymist-query/src/upstream/complete.rs
- crates/tinymist/src/server.rs
Don't trigger trivial completion when the trigger char is an ascii punctuation. Specifically, don't trigger them if the trigger character is one of:
- `:` and `,` for capturing parameter completion.
- `<` and `@` for capturing label completion.
- and more.
> feat: don't trigger trivial completion when trigger char is punc

- contrib/typlite/src/main.rs
- crates/tinymist-query/src/analysis/global.rs
- crates/tinymist-query/src/docs/convert.rs
- crates/tinymist-query/src/lib.rs
- crates/tinymist-query/src/syntax/docs.rs
- crates/tinymist/src/actor/mod.rs
- crates/tinymist/src/init.rs
- crates/typlite/src/lib.rs
- crates/typlite/src/library.rs
- crates/typlite/src/library/docstring.rs
- crates/typlite/src/tests.rs
- crates/typlite/src/tests/rendering.rs
- editors/vscode/package.json
- editors/vscode/src/config.ts
- editors/vscode/src/extension.ts
- editors/vscode/src/features/hover-storage.ts
- editors/vscode/src/state.ts
use `#example(str)` or `#example(raw)` to embed examples in docs. Tinymist will render these examples by `typst_svg::svg_merged` whenever possible.
> feat: render examples in docs

- MAINTAINERS.typ
- README.md
- package.json
- typ/templates/maintainer.typ
Get list of maintainers from [MAINTAINERS.typ](MAINTAINERS.typ). Or programmatically by `yarn maintainers`
> [!TIP]
> You can add extra arguments for specific information. For example, `yarn maintainers --input="action=maintainers"`.
> feat: claim list of maintainers

- crates/tinymist-query/src/docs/package.rs
- crates/tinymist-query/src/fixtures/hover/annotate_docs_error.typ
- crates/tinymist-query/src/fixtures/hover/snaps/test@annotate_docs_error.typ.snap
- crates/tinymist-query/src/syntax/docs.rs
- crates/tinymist-world/src/lib.rs
- crates/typlite/src/lib.rs
Previously, all content of documentation is gone if there is any error in docstring. Now we emit errors instead, so conversion never fails. The format of errors can be improved in future.
> feat: emit errors into docs instead of causing failures

- crates/tinymist-query/src/analysis/global.rs
This can be done confidently since https://github.com/Myriad-Dreamin/tinymist/pull/806
> feat: evict analysis caches before exact min revision

- crates/tinymist-query/src/package.rs
Previously, some directories are not identified because they are behind symbolic links.
> fix: query underlying file type when listing packages

- crates/tinymist-query/src/on_enter.rs
- crates/tinymist/src/server.rs
- editors/vscode/package.json
- editors/vscode/src/extension.ts
- editors/vscode/src/lsp.on-enter.ts
- editors/vscode/src/lsp.ts
The onEnter rules are borrowed from https://github.com/rust-lang/rust-analyzer/blob/fc98e0657abf3ce07eed513e38274c89bbb2f8ad/editors/code/src/config.ts#L98
- select with range
- select with multiple cursors
> feat: fully support `onEnter` edits inside comments

- editors/vscode/src/extension.ts
VSCode returns null if no configuration is provided even if we tell to use a default value. Moreover, a user might pass an invalid string, so we should redirect the default branch to "editorTab".
> fix: reliably check value of "tinymist.showExportFileIn"

- crates/tinymist-query/src/upstream/complete/ext.rs
A fix for #852
In short the crate pathdiff::diff_paths is used incorrectly. Here is an example:
```rust
assert_eq!(diff_paths("/foo/bar/quux", "/foo/bar/baz"),  Some("../quux".into())); // thus the following
assert_eq!(diff_paths("/foo/bar/image.jpg", "/foo/bar/file.typ"),  Some("../image.jpg".into()));
```
We might add more test to inspect other cases
> fix: wrong diff_path

- crates/tinymist-query/src/rename.rs
Example, rename `base.typ` to `test2.typ`:
```typ
#import "base.typ"
#include "base.typ"
#read("base.typ")
```
to
```typ
#import "test2.typ" as base
#include "test2.typ"
#read("test2.typ")
```
> feat: rename resource paths in files

- editors/vscode/package.json
- editors/vscode/src/extension.ts
- editors/vscode/src/features/dev-kit.ts
- editors/vscode/src/features/preview-compat.ts
- editors/vscode/src/features/preview.ts
- editors/vscode/src/lsp.on-enter.ts
- editors/vscode/src/lsp.ts
The upstream bugs might crash the language server in many cases, I feel it a requirement to have an explicit way to restart the language server client in such case.
> feat: restart server command in vscode

- Cargo.lock
- Cargo.toml
- editors/vscode/CHANGELOG.md
This is a massive update. See https://enter-tainer.github.io/typstyle/changelog/#v0122---2024-11-23 . Many thanks for @QuadnucYard !
> chore: bump typstyle to v0.12.3

- crates/tinymist-derive/src/lib.rs
- crates/tinymist-query/src/analysis/post_tyck.rs
- crates/tinymist-query/src/analysis/signature.rs
- crates/tinymist-query/src/analysis/tyck.rs
- crates/tinymist-query/src/analysis/tyck/syntax.rs
- crates/tinymist-query/src/fixtures/type_check/slow-subpar-super.typ.todo
- crates/tinymist-query/src/syntax/docs.rs
- crates/tinymist-query/src/ty/def.rs
- crates/tinymist-query/src/ty/mod.rs
- crates/tinymist-query/src/ty/simplify.rs
- crates/tinymist-query/src/ty/subst.rs
- crates/tinymist-query/src/upstream/complete/ext.rs
* case: package subpar:0.2.0
With deduplicating them early, time to type checking of `@preview/subpar:0.2.0` goes from 49 seconds to 0 seconds. Although we'll hold quite many hashsets which slows down checking of huge modules, but we might optimize the case later.
> dev: deduplicate type bounds early

- tools/editor-tools/src/features/template-gallery.ts
- tools/editor-tools/src/style.css
Basic search template gallery by name.
Will update with fuzzy finder, and search by description later.
Might also be nice to have search and insert universe for packages also.
> feat: search template gallery

- crates/tinymist-query/src/fixtures/hover/module_star_shadow.typ
- crates/tinymist-query/src/fixtures/hover/snaps/test@module_star_shadow.typ.snap
- crates/tinymist-query/src/syntax/expr.rs
In the example, `lib.draw` should be constant evaluated to know which symbols to import by wildcard (`*`).
```typ
/// path: draw.typ
/// The draw line.
#let line() = 1;
-----
/// path: lib.typ
#import "draw.typ"
-----
#import "lib.typ"
#import lib.draw: *
#(/* position after */ line);
```
> feat: resolve constant references in import at syntax level

- crates/tinymist-query/src/docs/def.rs
- crates/tinymist-query/src/fixtures/hover/snaps/test@annotate_dict_param2.typ.snap
- crates/tinymist-query/src/fixtures/hover/snaps/test@param.typ.snap
- crates/tinymist-query/src/hover.rs
- tests/e2e/main.rs
better hover on var:
```typst
#let d = (:)
^
|
let d = any; => let d = dictionary;
```
> fix: simplify types of variables for hover tooltip

- crates/tinymist-query/src/fixtures/completion/snaps/test@show_transform3.typ.snap
- crates/tinymist-query/src/upstream/complete/ext.rs
By moving site of enrich completions, snippets are also got enriched with space. For example:
```typ
#show:|
```
and select `transform`, it completes
```typ
#show: it => it
//    ^ added space in this PR
```
> feat: enrich all type completions consistently

- crates/tinymist-query/src/fixtures/completion/snaps/test@string_pos_arg.typ.snap
- crates/tinymist-query/src/fixtures/completion/string_pos_arg.typ
- crates/tinymist-query/src/upstream/complete.rs
- crates/tinymist-query/src/upstream/complete/ext.rs
Previously, type completion doesn't check surrounding syntax, e.g. whether it is inside of some string, thus completes some invalid results.
> feat: check surrounding syntax when performing type completion

- crates/tinymist-query/src/analysis/global.rs
- crates/tinymist-query/src/completion/snippet.rs
- crates/tinymist-query/src/upstream/complete.rs
- tests/e2e/main.rs
Almost all people may love to get a list of package completion items after completed import/include snippets, but this was prevented by auto decision by `tinymist.completion.triggerOnSnippetPlaceholders`.
> feat: explicitly trigger suggest after completed import/include snippets

- crates/tinymist/src/tool/preview.rs
- crates/typst-preview/src/actor/typst.rs
- crates/typst-preview/src/actor/webview.rs
- crates/typst-preview/src/lib.rs
- editors/vscode/e2e-workspaces/simple-docs/jump.typ
- tools/typst-preview-frontend/src/global.d.ts
- tools/typst-preview-frontend/src/typst.ts
- tools/typst-preview-frontend/src/ws.ts
> feat: jump to neareast position in preview from cursor

- crates/tinymist-query/src/analysis.rs
- crates/tinymist-query/src/analysis/definition.rs
- crates/tinymist-query/src/analysis/global.rs
- crates/tinymist-query/src/analysis/post_tyck.rs
- crates/tinymist-query/src/analysis/signature.rs
- crates/tinymist-query/src/completion.rs
- crates/tinymist-query/src/goto_declaration.rs
- crates/tinymist-query/src/goto_definition.rs
- crates/tinymist-query/src/hover.rs
- crates/tinymist-query/src/prelude.rs
- crates/tinymist-query/src/prepare_rename.rs
- crates/tinymist-query/src/references.rs
- crates/tinymist-query/src/rename.rs
- crates/tinymist-query/src/signature_help.rs
- crates/tinymist-query/src/syntax/matcher.rs
- crates/tinymist-query/src/upstream/complete/ext.rs
made some bikeshedding on names of matchers. The main changes are that the useless verb `get` is replaced by `classify`, which is commonly used by compilers checking some special syntax structures, and the noun `Target` is replaced by the corresponding noun of `classify`, i.e. `Class`. Among them, the core struct for ide functions is named as `SyntaxClass`, to refer the classes of syntax structure to be checked by ide functions. 
After naming, it should improve the readability, e.g. :
```patch
-   let deref_target = get_deref_target(leaf.clone(), cursor)?;
-   let def = ctx.def_of_syntax(source, document, deref_target.clone())?;
+   let syntax = classify_syntax(leaf.clone(), cursor)?;
+   let def = ctx.def_of_syntax(source, document, syntax.clone())?;
```
> refactor: improving names of matched structs and documenting matchers

- crates/tinymist-query/src/upstream/complete.rs
- tests/e2e/main.rs
> feat: comment complete for tidy style doc comment

- crates/tinymist-query/src/analysis/tyck/syntax.rs
- crates/tinymist-query/src/fixtures/completion/snaps/test@set_in_show.typ.snap
- crates/tinymist-query/src/fixtures/type_check/show.typ
- crates/tinymist-query/src/fixtures/type_check/show_raw.typ
- crates/tinymist-query/src/fixtures/type_check/show_raw_where.typ
- crates/tinymist-query/src/fixtures/type_check/snaps/test@show.typ.snap
- crates/tinymist-query/src/fixtures/type_check/snaps/test@show_raw.typ.snap
- crates/tinymist-query/src/fixtures/type_check/snaps/test@show_raw_where.typ.snap
Inferring `it` variables in following cases:
```typ
#show regex(":\S+:"): it => it
#show raw: it => it
#show raw.where(block: false): it => it
```
> feat: infer types of show rule transformers

- editors/vscode/src/lsp.ts
The word pattern was copied from some GitHub issue but it is not suitable for typst, at least we see a bug in #1053. That is we should not match dollar to identify a typst word. Bug cases:
Before fix:
```
$R
^^ word
$ R
^ word
$R$
^^^ word
```
After fix:
```
$R
^ word
$ R
^ word
$R$
^ word
```
> fix: typst language words should not contain dollars

- .github/workflows/release-vscode.yml
The universe target doesn't bundle the binary. This is suitable for other platforms like riscv64 or loongarch64. Users of that must install tinymist by themselves. Note it introduces risk to use unaligned version of the extension and the binary, but we can mitigate it in future.
> ci: build universe target vscode extension for other platforms

- docs/dev-guide.md
Building the docs via `yarn docs` wraps `shiroa`, I could not build them without first installing `shiroa` which should be stated clearly in the development guide.
> docs: state `shiroa` as a requirement

- tools/typst-dom/src/typst-doc.mts
- tools/typst-dom/src/typst-doc.svg.mts
In normal browsers, one can zoom in and out by `ctrl`+`wheel` and also by `ctrl`+`=` or `ctrl`+`-` . tinymist so far only supports the former. This pr adds support for the latter.
> feat: Rescaling with Ctrl+=/- in browser (in addition to ctrl+wheel)

- editors/vscode/e2e-workspaces/issue-1158/label-test.typ
- editors/vscode/src/features/label.ts
The labels tool view in vscode didn't work for documents with exactly one label. The error "items is not an iterable" was shown. This PR fixes that.
Before:
After:
> fix(vscode): make label view work when there's exactly one label

- editors/vscode/src/features/drag-and-drop.ts
Hi! This pr inherits the implementation of [excel-to-typst repo](https://github.com/hongjr03/excel-to-typst) into tinymist. Due to the limitations of the vscode API, I was only able to read the user's clipboard in HTML format via a shell call from the platform.
I have tested this on my MacBook (by developing a vscode extension), the Linux platform is not yet tested. On Windows platforms there may be problems with character encoding (UTF8 -> GBK -> UTF8) due to calls to powershell, not yet solved.
> feat: support convert to typst table from xlsx file

- Cargo.lock
- Cargo.toml
- crates/crityp/Cargo.toml
- crates/crityp/README.md
- crates/crityp/dist.toml
- crates/crityp/src/lib.rs
- crates/crityp/src/main.rs
Using the criterion.rs as the backend, it is pretty simple to create a bench tool. The PoC shows cold execution of the `fib(20)` in typst.
Example of execution:
```shell
crityp test-bench.typ
Benchmarking fib-bench typst
Benchmarking fib-bench typst: Warming up for 3.0000 s
Benchmarking fib-bench typst: Collecting 100 samples in estimated 5.2594 s (56k iterations)
Benchmarking fib-bench typst: Analyzing
test-bench.typ@fib-bench time:   [93.551 µs 94.220 µs 94.967 µs]    
change: [-91.268% -90.867% -90.520%] (p = 0.00 < 0.05)
Performance has improved.
Found 4 outliers among 100 measurements (4.00%)
3 (3.00%) high mild
1 (1.00%) high severe
```
Proposed design:
- can accept all arguments of `typst-cli compile`
- matches the exported function of the given main file. If the name of a function …
> feat: micro benchmark support

- editors/vscode/src/features/drag-and-drop.ts
Hi! 0.2.3 treat 0pt column width and row height as auto instead, and will parse table with dimensions as default.
> fix: update xlsx-parser package version to 0.2.3

- crates/tinymist-query/src/analysis/global.rs
- crates/tinymist-query/src/goto_definition.rs
- crates/tinymist-query/src/prepare_rename.rs
- crates/tinymist-query/src/references.rs
- crates/tinymist-query/src/rename.rs
- tests/e2e/main.rs
When a cursor is before a marker and after an identifier, the matcher will prefer to match the identifier instead of the marker.
For example, the following bars select the identifier:
```
#f(|xx)
#f(x|x)
#f(xx|)
```
> feat: prefer to select the previous token when cursor is before a marker

- crates/tinymist-project/src/watch.rs
- crates/tinymist-project/src/world.rs
- crates/tinymist-query/src/code_context.rs
- crates/tinymist-query/src/docs/convert.rs
- crates/tinymist-query/src/tests.rs
- crates/tinymist-vfs/src/dummy.rs
- crates/tinymist-vfs/src/lib.rs
- crates/tinymist-vfs/src/notify.rs
- crates/tinymist-vfs/src/overlay.rs
- crates/tinymist-vfs/src/resolve.rs
- crates/tinymist-vfs/src/snapshot.rs
- crates/tinymist-vfs/src/trace.rs
- crates/tinymist-world/src/entry.rs
- crates/tinymist-world/src/font/resolver.rs
- crates/tinymist-world/src/lib.rs
- crates/tinymist-world/src/package/mod.rs
- crates/tinymist-world/src/source.rs
- crates/tinymist-world/src/world.rs
- crates/tinymist/src/actor/mod.rs
- crates/tinymist/src/actor/typ_server.rs
- crates/tinymist/src/server.rs
- crates/tinymist/src/task/cache.rs
- crates/tinymist/src/tool/preview.rs
- crates/typlite/src/lib.rs
- will close #763 in later PR
- close #336
- The world's revision is increased by VFS changed only if any compilation-related content is changed.
- This was not operatable because both analyzers and the compiler will access the world and touch the files. We were not able to distinguish whether an content is ever accessed by the compiler and not only accessed by the analyzers *after some vfs changes*.
- Each file (`VfsEntry`) has a revision. `Vfs` starts to cache and respond same content on an entry unless the associated cache is explicitly invalidated. This strategy is used by the ruff-lsp.
- `invalidate_file_id`: The entry corresponds to the `file_id` is invalidated. An entry may have no path if it is an in-memory nameless buffer.
- `invalidate_path`: Mulitple `file_id`s can be mapped to …
> feat: track fine-grained revisions of `font`, `registry`, `entry`, and `vfs`

- crates/typst-preview/src/actor/render.rs
This was broken by #1156, same as #1159. @Enter-tainer
> fix: push resolved span to editor

- Cargo.lock
- crates/tinymist-project/src/args.rs
- crates/tinymist-project/src/entry.rs
- crates/tinymist-project/src/lock.rs
- crates/tinymist-project/src/model.rs
- crates/tinymist-query/src/analysis.rs
- crates/tinymist/Cargo.toml
- crates/tinymist/src/lib.rs
- crates/tinymist/src/route.rs
- crates/tinymist/src/server.rs
- crates/tinymist/src/task/export.rs
- crates/tinymist/src/tool/project.rs
Although we have great multiple-files project support in VS Code, we still experiment a sample implementation in VS Code. The new mechanism is put behind a flag. It isn't enabled by default. You can also only use the `lockDatabase` in some specific workspaces.
- the CLI or server will update the lock file if one invokes compile/preview commands via CLI or LSP.
- the server will see the lock file to see what's the best main file to use:
- If _a file_ is depended by some unique main file recorded in the lock, the main file is used.
- If _a file_ is depended by multiple main files, the most recently recorded main file wins.
- otherwise, the language server sets the main file to _the file_ itself.
Even if there is no any editor-side (client-side) additional support, people should be able to …
> feat: resolve projects by `lockDatabase`

- crates/tinymist-project/src/args.rs
- crates/tinymist-project/src/lock.rs
- crates/tinymist-project/src/model.rs
- crates/tinymist-project/src/model/task.rs
- crates/tinymist-query/src/lib.rs
- crates/tinymist-world/src/args.rs
- crates/tinymist/src/cmd.rs
- crates/tinymist/src/init.rs
- crates/tinymist/src/state/input.rs
- crates/tinymist/src/state/project.rs
- crates/tinymist/src/state/server.rs
- crates/tinymist/src/task/export.rs
- crates/tinymist/src/tool/preview.rs
- crates/tinymist/src/tool/project.rs
A task is serializable, which is locked in the lock file. A task consists of the `input` id, `output` pattern, `when` to execute, and the task-specific configuration (parameters). The export function is refactored and execute on the task's configuration.
> feat: execute export and query on the task model

- crates/tinymist/src/task/user_action.rs
- crates/tinymist/src/tool/preview.rs
Simpler alternative to #1093 that does not break any downstream packages.
However, this does _not_ provide protection on multi-user systems where users don't trust each other. It only prevents websites other than `127.0.0.1` from connecting to our servers. So it's a good first step but doesn't cover all scenarios.
One question:
I noticed there's a second `make_http_server` function that explicitly sets `Access-Control-Allow-Origin: *`. What is that server used for? Obviously, the `*` CORS header looks dangerous.
https://github.com/Myriad-Dreamin/tinymist/blob/8e918cb1322c67160a516c7478d6ecd7a444f014/crates/tinymist/src/task/user_action.rs#L227-L264
> fix: Prevent malicious websites from connecting to http / websocket server

- crates/tinymist-project/src/model.rs
- crates/tinymist/src/args.rs
- crates/tinymist/src/main.rs
- crates/tinymist/src/tool/project.rs
- package.json
- scripts/project-build.ps1
Persist commands in the lock file as a shell script:
```bash
tinymist compile --save-lock --task 'file:docs/tinymist/book.typ' 'docs/tinymist/book.typ' --root '.' --format=pdf
tinymist compile --save-lock --task 'ebook-cover' 'docs/tinymist/ebook.typ' --root '.' --pages 1-1 --format=svg
tinymist compile --save-lock --task 'file:docs/tinymist/ebook.typ' 'docs/tinymist/ebook.typ' --root '.' --format=pdf
```
This is currently not an external feature, but used for round-trip testing, like:
- The lockfile is upgradable and downgradable by the shell script.
- tinymist doesn't change a lockfile if it executes and persists the exported commands from the same lockfile.
> feat: CLI generate shell build script

- crates/tinymist-task/src/compute/pdf.rs
This is possibly not a valid fix, but just make errors silent
> fix: panic on convert_datetime

- crates/typlite/README.md
- crates/typlite/src/lib.rs
- Embed Markdown codes
Raw codes with `typlite` language will not be treated as a code block but directly output into the Markdown result.
> feat: embed Markdown codes

- Cargo.lock
- crates/tinymist-vfs/Cargo.toml
- crates/tinymist-vfs/src/lib.rs
* fix: don't clean path mapping when invalidate vfs cache
* fix: remove duplicated insert
* refactor: name
> fix: don't remove path mapping when invalidating vfs cache (#1316)

- crates/typst-preview/src/actor/editor.rs
- crates/typst-preview/src/actor/webview.rs
- crates/typst-preview/src/lib.rs
The broadcast channels can return error when the editor or the browser hasn't created connection with the preview server.
> fix: log error on channel closed

- crates/tinymist/src/project.rs
- crates/tinymist/src/tool/preview.rs
* fix: add console diagnostics printing back
* feat: print conditionally
> fix: add console diags printing back for `tinymist preview` (#1359)

- crates/tinymist-std/Cargo.toml
Context: https://github.com/NixOS/nixpkgs/pull/383763
CC @GaetanLepage
We may fix all of them once. I now have only fixed features in the `tinymist-std`.
> fix: simplify dependency features in cargo.toml

- Cargo.lock
- Cargo.toml
- crates/tinymist-core/package.json
- editors/vscode/CHANGELOG.md
- editors/vscode/package.json
- syntaxes/textmate/package.json
Small note: v0.13+ use typst v0.13.0, while v0.12+ continue using typst v0.12.0. The v0.12+ will be maintainted until most people move to v0.13+ or it takes too much cost to backport patches.
> build: bump version to 0.12.22

- Cargo.lock
- Cargo.toml
- crates/tinymist-core/package.json
- editors/vscode/CHANGELOG.md
- editors/vscode/package.json
- syntaxes/textmate/package.json
Small note: v0.13+ use typst v0.13.0, while v0.12+ continue using typst v0.12.0. The v0.12+ will be maintainted until most people move to v0.13+ or it takes too much cost to backport patches.
> build: bump version to 0.13.0

- crates/tinymist-query/src/ty/describe.rs
- crates/tinymist-vfs/src/path_mapper.rs
- tests/e2e/main.rs
typst v0.13.0 can have module objects that don't have a name or even a file path:
- plugins are modules now.
- in future, there might be some in-place created modules `let m = module { let x = 1 }`.
> feat: print type representation of anonymous modules

- crates/tinymist/src/init.rs
Use `Config::new` instead of `Config::default` to create a config on start of server.
> Note: `Config::default` is intentionally to be "pure" and not to be affected by system environment variables. To get the configuration with system defaults, use [`Config::new`] intead.
> feat: let `tinymist::Config` pull environment variables on start of server

- Cargo.lock
- Cargo.toml
- editors/vscode/Configuration.md
- tools/typst-dom/package.json
- tools/typst-preview-frontend/package.json
- yarn.lock
The repr of `VecItem` in the backend (compiler, v0.5.5) is imcompatible that in the frontend (renderer, v0.5.4).
> fix: use new wasm renderer

- crates/tinymist/src/tool/preview.rs
- crates/typst-preview/src/actor/render.rs
- crates/typst-preview/src/actor/webview.rs
- crates/typst-preview/src/lib.rs
- tools/typst-dom/src/typst-debug-info.mts
- tools/typst-dom/src/typst-doc.svg.mts
Things are changing. Three reasons as follow:
+ Accessiblilty to the world in the past: the world now completely becomes a cheap snapshot and we can hold the exact world compiled the document, to consistently serve preview requests.
+ Room to improvement resolution: We have [reflexo-vec2bbox](https://crates.io/crates/reflexo-vec2bbox) which can resolve all bbox at server side. We can resolve any typst elements within any geometric transformation.
+ Unlock the in-loop optimizations: It gives more opportunities to optimize the output slightly. We were not able to perform any optimization because it was resolving source span by element paths, and optimization completely ruins the path-span correspondance.
> feat: use `jump_from_click` from typst-ide

- crates/tinymist-query/src/analysis/completion/type.rs
- crates/tinymist-query/src/fixtures/pkgs/snaps/test@touying-utils-current-heading.typ-2.snap
- crates/tinymist-query/src/fixtures/pkgs/snaps/test@touying-utils-markup-text.typ.snap
- tests/e2e/main.rs
completes `regex` to `regex(${1})` instead of `${1:regex}`
> fix: complete type of type having constructors

- editors/vscode/package.json
This works around VS Code's undocumented behavior which is described in https://github.com/microsoft/vscode-docs/issues/7773 that language specific settings for a single language take precedence over language specific settings set for multiple languages the same time. Before this change, if a user wanted to overwrite the defaults, they would have to set it for each language individually.
After this change, users can overwrite `configurationDefaults` whether or not they chose to specify them for one language or multiple languages at the same time. Fixes #1460.
> fix: combine VS Code language specific default settings into one block

- Cargo.lock
- Cargo.toml
- benches/font-load/Cargo.toml
- benches/font-load/src/load.rs
- crates/tinymist-world/Cargo.toml
- crates/tinymist-world/src/font/system.rs
- crates/tinymist/src/init.rs
- crates/tinymist/src/project.rs
- package.json
It is buggy to load fonts asynchronously. We now load it synchronously but with some parallelization optimization.
Without Parallelization:
```
Timer precision: 17 ns
tinymist_bench_font_load  fastest       │ slowest       │ median        │ mean          │ samples │ iters
├─ load_embedded          1.167 ms      │ 1.697 ms      │ 1.176 ms      │ 1.188 ms      │ 100     │ 100
╰─ load_system            111.8 ms      │ 123 ms        │ 113.6 ms      │ 114.3 ms      │ 100     │ 100
```
With Parallelization:
```
Timer precision: 17 ns
tinymist_bench_font_load  fastest       │ slowest       │ median        │ mean          │ samples │ iters
├─ load_embedded          130.8 µs      │ 1.164 ms      │ 157 µs        │ 170.3 µs      │ 100     │ 100
╰─ load_system            14.44 ms      │ 18.22 ms …
```
> perf: parallelize font loading and sync wait it

- Cargo.lock
- Cargo.toml
- crates/tinymist/src/cmd.rs
- crates/tinymist/src/task/user_action.rs
- editors/vscode/src/features/tool.ts
Add profile-server prototype. 
- Requires Myriad-Dreamin/typst#4
- The UI is temporary and only intended for testing purposes.
- Source code information in tracing data is not resolved correctly.
- Different compilation actions cannot be distinguished for now.
> feat: add profile-server prototype

- crates/tinymist/src/tool/preview.rs
Supersedes https://github.com/Myriad-Dreamin/tinymist/pull/1321
Mostly just cleanup, with a few behavior changes:
- Allows only https for gitpod (not http)
- Disallows any paths in Origin header (see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin#syntax)
- Allow a mismatch in ports only for localhost/127.0.0.1
- Always allow requests without any `Origin` header (the idea being that browsers do always send an `Origin` when it's important, in the meantime that same behavior was also added in https://github.com/Myriad-Dreamin/tinymist/pull/1411)
> fix: cleanup CORS checks (v2)

- CHANGELOG/CHANGELOG-2024.md
- README.md
- crates/tinymist/src/input.rs
- docs/tinymist/book.typ
- docs/tinymist/feature/preview.typ
- docs/tinymist/frontend/main.typ
- docs/tinymist/frontend/neovim.typ
- docs/tinymist/introduction.typ
- editors/neovim/Configuration.md
- editors/neovim/README.md
- editors/vscode/CHANGELOG.md
- editors/vscode/Configuration.md
- editors/vscode/src/config.ts
- locales/tinymist-vscode.toml
From the https://neovim.io/ it's clearly seen that the proper naming would be "Neovim" and not "NeoVim". This PR fixes the casing and also capitalizes the first letter wherever is necessary. I would've automated it, but there are a lot of places where it's used as a part of a path etc., so I went through all files manually.
> docs: fix Neovim name casing everywhere

- scripts/link-docs.mjs
See https://github.com/Myriad-Dreamin/tinymist/pull/1521#issuecomment-2727805390 for details.
> build: fix docs:typ using wrong root dir

- crates/tinymist-debug/src/cov.rs
- crates/tinymist-debug/src/lib.rs
- crates/tinymist-project/src/args.rs
- crates/tinymist-project/src/world.rs
- crates/tinymist-query/src/lib.rs
- crates/tinymist-query/src/testing/mod.rs
- crates/tinymist/src/args.rs
- crates/tinymist/src/main.rs
- crates/tinymist/src/tool/mod.rs
- crates/tinymist/src/tool/project.rs
- crates/tinymist/src/tool/testing.rs
- docs/tinymist/book.typ
- docs/tinymist/feature/testing.typ
- editors/vscode/package.json
- editors/vscode/src/context.ts
- editors/vscode/src/features/testing/coverage.ts
Adds a command `tinymist test` that use code analysis to discover tests associated with a document. This is useful to collect coverage of some entire package in CI.
Example:
```
// in tests.typ
#let test-func-a() = [...]
#let test-func-b() = [...]
#let bench-func-b() = [...]
#let panic-on-func-b() = [...]
// As long as the other modules are referenced by this file, tinymist will run the tests inside of them as well.
#import "example-doc.typ"
#import "sub-module/tests.typ"
```
CI command:
```
$ tinymist test src/tests.typ --root . --font-path assets/fonts
Found 40 tests and 15 examples
Running test test-func-a
Running test test-func-b
Passed test test-func-b
Passed test test-func-a
Running test bench-func-b # bench function is also run once for testing
Passed test bench-func-b
Running test …
```
> feat: add test framework with coverage support

- crates/tinymist-query/src/fixtures/folding_range/block-in-list-enum.typ
- crates/tinymist-query/src/fixtures/folding_range/list-enum.typ
- crates/tinymist-query/src/fixtures/folding_range/nested-list-enum.typ
- crates/tinymist-query/src/fixtures/folding_range/snaps/test@block-in-list-enum.typ.snap
- crates/tinymist-query/src/fixtures/folding_range/snaps/test@list-enum.typ.snap
- crates/tinymist-query/src/fixtures/folding_range/snaps/test@nested-list-enum.typ.snap
- crates/tinymist-query/src/syntax/lexical_hierarchy.rs
An attempt to fix #1265. Currently it can only fold the content of an list/enum item, not a sequence of adjacent items.
Actually I'm not really sure about these changes, please check if there's any problems!
> feat: fold list and enum item content

- Cargo.lock
- Cargo.toml
- crates/tinymist-project/Cargo.toml
- crates/tinymist-query/Cargo.toml
- crates/tinymist-std/Cargo.toml
- crates/tinymist-std/src/time.rs
- crates/tinymist-task/Cargo.toml
- crates/tinymist-task/src/compute/pdf.rs
- crates/tinymist-world/Cargo.toml
- crates/tinymist-world/src/args.rs
- crates/tinymist-world/src/world.rs
- crates/tinymist/src/task/export.rs
This prevents building crates to `wasm-unknown-unknown`.
> fix: remove system time deps from crates

- tools/typst-preview-frontend/src/drag.ts
fixes #1111
| action              | before this PR                 | after            |
| ------------------- | ------------------------------ | ---------------- |
| click on empty area | selection flashes, as in #1111 | clears selection |
| during dragging     | selection is hidden            | shown            |
selection is retained after dragging, as before
> fix: in preview, click on empty area now clears selection

- crates/tinymist-lint/src/lib.rs
- crates/tinymist-query/src/fixtures/lint/good_font.typ
- crates/tinymist-query/src/fixtures/lint/snaps/test@good_font.typ.snap
- crates/tinymist-query/src/fixtures/lint/snaps/test@vf.typ.snap
- crates/tinymist-query/src/fixtures/lint/snaps/test@vf_object.typ.snap
- crates/tinymist-query/src/fixtures/lint/vf.typ
- crates/tinymist-query/src/fixtures/lint/vf_object.typ
Please let me know if and how we can do better on this, for example:
1. resolve font info and see if it's vf or not(instead of check if it ends with "VF")
2. handle cases where fonts are not directly visible in ast
> feat(lint): add warning for vf font

- editors/vscode/package.json
I've added, for me, meaningful values for the settings `tinymist.formatterMode` and `tinymist.fontPaths`.
With this change it is possible to
- format `*.typ` without having to make changes to the settings (by default).
~~- use fonts, that are present in the `fonts` folder inside the workspace.~~
If you guys also think this setting makes sense, I would love to see this MR being merged. (:
> feat: reasonable default values for settings for formatterMode

- crates/tinymist-lint/src/lib.rs
- crates/tinymist-query/src/fixtures/lint/return_loop3.typ
- crates/tinymist-query/src/fixtures/lint/return_partial_if.typ
- crates/tinymist-query/src/fixtures/lint/snaps/test@return_loop3.typ.snap
- crates/tinymist-query/src/fixtures/lint/snaps/test@return_partial_if.typ.snap
the pattern caused false positive:
```typ
#let get-op(offset, op) = {
op = if offset < 0 { "<=" } else { ">=" }
return op
}
```
This could be viewed as `op = "<="`, so the string is not discarded by `op`
> fix: the block is assumed to be used in expressions

- editors/vscode/src/extension.ts
pattern, when vscode swtich files (by goto definition), it first close the previous doc and open the next doc.
```cjs
focus(@preview/cetz:0.3.4/lib.typ)
focus(undefined)
focus(@preview/cetz:0.3.4/canvas.typ)
```
This will cause unnecessary root change when viewing package source files. server internally does:
```cjs
change(root: /cache/preview/cetz/0.3.4, main: src/lib.typ)
change(root: /doc/root, main: None) // resetting root, all analysis cache lose
change(root: /cache/preview/cetz/0.3.4, main: src/canvas.typ) // resetting root, all analysis cache lose
```
We'll definitely be able to make root resolving stateful, but I may look if we could do that gracefully then.
> feat: delay doc switch

- docs/tinymist/frontend/neovim.typ
- editors/neovim/README.md
Closes #1671 
I also updated the single quotes to double quotes to better fit the style of the surrounding code blocks.
> docs: Fix syntax error in Neovim docs

- crates/tinymist-query/src/analysis/completion.rs
- crates/tinymist-query/src/analysis/completion/field_access.rs
- crates/tinymist-query/src/analysis/completion/kind.rs
- crates/tinymist-query/src/analysis/completion/scope.rs
- crates/tinymist-query/src/analysis/completion/snippet.rs
- crates/tinymist-query/src/analysis/completion/typst_specific.rs
- editors/vscode/package.json
The configuration `tinymist.completion.symbol` is to determine whether to make symbol completion stepless. For example, 
- `$ar|$` could be completed to `$arrow.r$`,
- `$arrow.tbsd|$` could be completed to `$arrow.t.b.stroked$`,
- and `$paseet|$` could be completed to `$parallel.slanted.eq.tilde$`.
This feature is disabled by default.
> feat: optionally make symbol completion stepless

- docs/tinymist/frontend/neovim.typ
- editors/neovim/README.md
- editors/neovim/plugins/tinymist.lua
Related to #1670 and #1595.
Should not be merged until #1670 is resolved.
> docs: Change pinning to use non-deprecated function `client:exec`

- crates/tinymist-std/src/path.rs
We generally call a relative path "from a base to a target".
The original code seems made a mistake in naming "to" and "from".
> fix: correct parameter name in `diff` function for clarity

- crates/tinymist-query/src/analysis/link_expr.rs
- crates/tinymist-query/src/fixtures/document_link/bibliography_csl.typ
- crates/tinymist-query/src/fixtures/document_link/snaps/test@bibliography_csl.typ.snap
> fix: built-in CSL styles are recognized as path link

- crates/tinymist-vfs/src/lib.rs
- crates/tinymist-world/src/world.rs
Sometimes, the tools may like read all the things from the system again.
> feat: model and make `reset_read` public

- crates/tinymist-package/src/registry.rs
- crates/tinymist-package/src/registry/memory.rs
Package registry implementation in memory extracted from the embedded typst plugin, which could be used in no-std environments, for example, in a typst plugin.
> feat: add memory registry

- crates/typlite/src/fixtures/integration/snaps/convert_tex@base.typ.snap
- crates/typlite/src/fixtures/integration/snaps/convert_tex@enum.typ.snap
- crates/typlite/src/fixtures/integration/snaps/convert_tex@enum2.typ.snap
- crates/typlite/src/fixtures/integration/snaps/convert_tex@figure_caption.typ.snap
- crates/typlite/src/fixtures/integration/snaps/convert_tex@figure_image.typ.snap
- crates/typlite/src/fixtures/integration/snaps/convert_tex@figure_image_alt.typ.snap
- crates/typlite/src/fixtures/integration/snaps/convert_tex@image.typ.snap
- crates/typlite/src/fixtures/integration/snaps/convert_tex@image_alt.typ.snap
- crates/typlite/src/fixtures/integration/snaps/convert_tex@link.typ.snap
- crates/typlite/src/fixtures/integration/snaps/convert_tex@link2.typ.snap
- crates/typlite/src/fixtures/integration/snaps/convert_tex@link3.typ.snap
- crates/typlite/src/fixtures/integration/snaps/convert_tex@list.typ.snap
- crates/typlite/src/fixtures/integration/snaps/convert_tex@math_block.typ.snap
- crates/typlite/src/fixtures/integration/snaps/convert_tex@math_block2.typ.snap
- crates/typlite/src/fixtures/integration/snaps/convert_tex@math_inline.typ.snap
- crates/typlite/src/fixtures/integration/snaps/convert_tex@outline.typ.snap
- crates/typlite/src/fixtures/integration/snaps/convert_tex@raw_inline.typ.snap
- crates/typlite/src/fixtures/integration/snaps/convert_tex@table.typ.snap
- crates/typlite/src/lib.rs
- crates/typlite/src/main.rs
- crates/typlite/src/parser/core.rs
- crates/typlite/src/parser/media.rs
- crates/typlite/src/tests.rs
- crates/typlite/src/writer/latex.rs
- crates/typlite/src/writer/mod.rs
There are unresolved questions from #1684:
> elements created by the user calling `html.frame` inside that have predefined display rules applied to them may lead to unexpected results, which needs some further discussions i think?
> 
> for example:
> 
> ```typst
> #html.frame(
>   grid(columns: 2, [hello], [world])
> )
> ```
> 
> will render nothing in result.
> another issue should be concerned:
> 
> ```typst
> show figure: it => md-figure(it.body, caption: it.caption.body)
> ```
> 
> As caption can also be `content` type, what should we do to make this show rule work properly in all scene?
> feat: typlite supports latex export

- crates/tinymist-analysis/src/syntax/matcher.rs
- crates/tinymist-query/src/analysis/completion.rs
- crates/tinymist-query/src/analysis/definition.rs
- crates/tinymist-query/src/analysis/post_tyck.rs
- crates/tinymist-query/src/fixtures/completion/snaps/test@ref_half_colon2.typ.snap
- crates/tinymist-query/src/references.rs
The typst parser doesn't parse the colon in the following case into a reference node:
```typ
@ab:
```
This PR re-identifies such syntax for IDE operations.
> feat: re-identify ref colon syntax and perform IDE operations

- crates/tinymist-query/src/analysis/code_action.rs
- crates/tinymist-query/src/analysis/completion.rs
- crates/tinymist-query/src/analysis/global.rs
- crates/tinymist-query/src/analysis/link_expr.rs
- crates/tinymist-query/src/analysis/tyck.rs
- crates/tinymist-query/src/code_action.rs
- crates/tinymist-query/src/code_action/proto.rs
- crates/tinymist-query/src/fixtures/code_action/snaps/test@absolute_path_import.typ.snap
- crates/tinymist-query/src/fixtures/code_action/snaps/test@path_and_equation.typ.snap
- crates/tinymist-query/src/fixtures/code_action/snaps/test@path_import.typ.snap
- crates/tinymist-query/src/fixtures/code_action/snaps/test@path_json.typ.snap
- crates/tinymist-query/src/jump.rs
- crates/tinymist-query/src/lib.rs
- crates/tinymist-query/src/prelude.rs
- crates/tinymist-query/src/signature_help.rs
- crates/tinymist-query/src/tests.rs
- crates/tinymist-vfs/src/path_mapper.rs
- crates/tinymist/src/config.rs
- crates/tinymist/src/lsp/query.rs
- crates/tinymist/src/project.rs
- editors/vscode/Configuration.md
- editors/vscode/src/extension.shared.ts
- editors/vscode/src/extension.ts
- editors/vscode/src/lsp.code-action.ts
- editors/vscode/src/lsp.ts
- editors/vscode/src/util.ts
- tests/fixtures/initialization/vscode-1.87.2.json
from:
```typ
// unknown variable: first-item
#todo-list(first-item, second-item)
```
to 
```typ
#let ${1:first-item} = ${2:none}
#todo-list(first-item, second-item)
```
from:
```typ
// file not found (searched at a.typ)
#include "a.typ"
```
to 
```typ
// a.typ
$0
```
> feat: autofix `unknown variable: a` and `file not found (searched at a.typ)` by code action

- crates/tinymist-project/src/entry.rs
- crates/tinymist-project/src/model.rs
- crates/tinymist-query/src/tests.rs
- crates/tinymist-task/src/primitives.rs
- crates/tinymist-tests/src/lib.rs
- crates/tinymist/src/config.rs
The dummy root path /root conflicts with root user's home directory on Linux and redacts incorrectly:
```
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot file: crates/tinymist-query/src/fixtures/goto_definition/snaps/test@import_package_self.typ.snap
Snapshot: test@import_package_self.typ
Source: crates/tinymist-query/src/goto_definition.rs:74
Input file: crates/tinymist-query/src/fixtures/goto_definition/import_package_self.typ
──────────────────────────────────────────────────────────────────────────────────────
Expression: JsonRepr::new_redacted(result, &REDACT_LOC)
──────────────────────────────────────────────────────────────────────────────────────
-old snapshot
+new results
────────────┬───────────────────────────────────────────────── …
```
> fix(test): running test as root

- Cargo.lock
- Cargo.toml
- contrib/html/editors/vscode/package.json
- crates/tinymist-core/package.json
- editors/vscode/package.json
- syntaxes/textmate/package.json
> build: bump version to 0.13.14-rc3

- editors/vscode/src/lsp.ts
Showing svg with vscode remote is hated by vscode. The SVG links in the remote machine will be sanitized for security reason. references:
- https://github.com/James-Yu/LaTeX-Workshop/blob/a0267e507867ae8be94b48a70d0541865fcf905f/src/preview/hover/ongraphics.ts
- https://github.com/microsoft/vscode/issues/137632
- https://github.com/microsoft/vscode/issues/97759
> fix: show svg on hover in vscode-remote

- tools/typst-preview-frontend/src/styles/layout.css
Reverts Myriad-Dreamin/tinymist#1887
In test of v0.13.16-rc2, The CSS doesn't work as expected when previewing in both tab and browser.
> revert: "feat: auto-hide presentation toolbar when not hovered"

- crates/tinymist-project/src/compiler.rs
- crates/tinymist-project/src/lib.rs
- crates/tinymist-world/src/snapshot.rs
- crates/tinymist/src/project.rs
- crates/tinymist/src/task/export.rs
This bugs involves two main component: the compiler and the exporter, the compiler compiles first and then exporter exports then. it is useful to emit `CompileSignal::by_fs_events` to exporter even if vfs is clean at the time we save a document.
An example triggering this bug. When user sets `exportPdf` to `onSave`, It *bugged*:
1. OnTyped first: User types some character at T1. compiler learns that the file content is of revision R1. the compiler compiles with revision R1, which is needed by diagnostics event.
2. OnSaved then: Editor saves the document at T2. the compilation is skipped early because file content is still under revision R1. In previous version, The compilation is skipped and therefore the export is also skipped. This is *bugged* if user sets `exportPdf` to `onSave`, …
> fix: emit onSaved signal to exporter when vfs is clean

- crates/tinymist-project/src/args.rs
- crates/tinymist/src/task/export.rs
This change ensures that user-specified output paths in the compile command are properly handled, including relative paths.
Previously, the export task would reject relative output paths with an error. This change converts relative paths to absolute paths by joining them with the current working directory, allowing users to specify relative paths like 'output/test.pdf' when compiling documents.
The fix adds path normalization using PathClean and handles the conversion gracefully while maintaining the existing behavior for absolute paths.
Fixes the issue where commands like:
tinymist compile resume-en.typ ./output/test.pdf
would fail with "output path is relative" error.
> fix: correctly handle relative user-specified output paths in compile command

- contrib/nix/dev/flake.nix
- flake.lock
- flake.nix
by default, we assume people would like develop the language server and editor tools. The building of tinymist-cli is moved to the neovim shell.
> feat: add rust and yarn to nix devShell

- .github/workflows/ci.yml
According to https://github.com/actions/runner/issues/1007, the push events was not created when bot creating tags.
> fix(ci): detect create intead of push

- crates/tinymist/src/project.rs
Otherwise, `pending_reasons` is cleared.
> fix: don't check or change state if no reasons

- crates/tinymist-analysis/src/docs.rs
- crates/tinymist-analysis/src/docs/tidy.rs
- crates/tinymist-query/src/docs/package.rs
- crates/tinymist-query/src/fixtures/hover/snaps/test@render_equation.typ.snap
When there's HTML comments in list, the markdown syntax won't be parsed as expected. This pr cleans typlite markers from doc string to avoid this behavior.
> fix: clean typlite markers from doc strings

- crates/tinymist-query/src/check.rs
- crates/tinymist-query/src/code_action.rs
- crates/tinymist-query/src/diagnostics.rs
> Hm. Sorry about the lint failures here, they slipped my attention locally since they show up as warnings, not errors, in my editor. I'm happy to put a PR fixing them later unless you get to it first.
>
> Not too sure how to deal with the unused DiagWorker::check method, since it is used, just in a test-only module. We can certainly mark it as #[cfg(test)] but that feels a little nasty.
https://github.com/Myriad-Dreamin/tinymist/pull/2062#issuecomment-3237812684
I ended up inlining the logic of `DiagWorker::check` into the test.
> dev: fix lint warnings introduced by #2062

- crates/tinymist/src/tool/preview/http.rs
- editors/vscode/src/features/preview.ts
Previously, Tinymist preview does not work on VS Code web (code-server) because it tries to connect to the `localhost`, which is impossible since we are doing remote development.
Even if we fix this error, the HTTP origin check will also fail because the domain of our VS Code web is not trusted by Tinymist. One possible fix is to grab the `VSCODE_PROXY_URI` environment variable and check if the incoming request matches the URI. This will fix the issue for most standard code-server installations.
However, GitHub Codespace is an exception. I did some logging, and found that GitHub Codespace used different origins:
- `<random>.assets.github.dev`
- `https://localhost:<port>` (note HTTP**S**)
- `None`
This is very weird and difficult to debug. Moreover, the ports forwarded by GitHub Codespaces …
> fix: extend origin check for vscode servers

- crates/tinymist-lint/src/lib.rs
- crates/tinymist-project/src/compiler.rs
- crates/tinymist-query/src/check.rs
- crates/tinymist-world/src/compute.rs
This requires new release of world crates, while we didn't plan it.
> fix: remove `Clone` trait bounds from diagnostics iterators
